### ISSUE TITLE
KeyError: 'feedback' in some post

### ISSUE THREAD

**Issue by Jia35** [kevinzg/facebook-scraper#107]
Hi
I encountered a problem when I crawled `https://www.facebook.com/pg/ETtoday/posts/`.
```
【https://facebook.com/story.php?story_fbid=3683417108361093&id=242305665805605】
【https://facebook.com/story.php?story_fbid=3683487731687364&id=242305665805605】
【https://facebook.com/story.php?story_fbid=3683353441700793&id=242305665805605】
【https://facebook.com/story.php?story_fbid=3683359271700210&id=242305665805605】
============================
Traceback (most recent call last):
  File "FBfanpage_crawler.py", line 92, in job
    crawler_task.run()
  File "FBfanpage_crawler.py", line 153, in run
    for post_block in get_posts(fanpage_id, pages=4, extra_info=True):
  File "D:\Desktop\python_crawler\python_crawler\crawlerwork\tool\facebook_scraper\facebook_scraper.py", line 98, in _generic_get_posts
    yield extract_post_fn(post_element, options=options, request_fn=self.get)
  File "D:\Desktop\python_crawler\python_crawler\crawlerwork\tool\facebook_scraper\extractors.py", line 27, in extract_post
    return PostExtractor(raw_post, options, request_fn).extract_post()
  File "D:\Desktop\python_crawler\python_crawler\crawlerwork\tool\facebook_scraper\extractors.py", line 119, in extract_post
    reactions = self.extract_reactions()
  File "D:\Desktop\python_crawler\python_crawler\crawlerwork\tool\facebook_scraper\extractors.py", line 314, in extract_reactions
    ]['feedback']
KeyError: 'feedback'
File "D:\Desktop\python_crawler\python_crawler\crawlerwork\tool\facebook_scraper\extractors.py", line 314, in extract_reactions: [KeyError] feedback
```
The wrong POST should be `https://m.facebook.com/story.php?story_fbid=3683420668360737&id=242305665805605`.

I currently use `try-except` to skip it. Is there any way to solve this?
Thank you very much.

**Comment by balazssandor** [comment]
I have made this fix on my end
![image](https://user-images.githubusercontent.com/32865690/92601938-1942cf80-f2b6-11ea-9482-a9dc1ded9e76.png)

**Comment by neon-ninja** [comment]
```python
posts = list(get_posts(
    post_urls=[3683420668360737],
    extra_info = True,
    timeout = 60,
    cookies = "cookies.txt"
))
for post in posts:
    print(post.get("reactions"))
```
outputs
```python
{'like': 460, 'love': 2, 'haha': 35, 'wow': 50, 'care': 3, 'sad': 21, 'angry': 1907}
```

So this seems fixed
