### ISSUE TITLE
Login Fail

### ISSUE THREAD

**Issue by 2849232wy** [kevinzg/facebook-scraper#1091]
import facebook_scraper
from facebook_scraper import get_posts

facebook_scraper.set_user_agent("Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36")
for post in get_posts('nintendo', pages=1, credentials=("xxx","xxx")):
    print(post['text'][:50])

Traceback (most recent call last):
  File "F:\facebook\TestPosts.py", line 7, in <module>
    for post in get_posts('nintendo', pages=1, credentials=("xxx","xxxx")):
  File "C:\Program Files\python3.9\lib\site-packages\facebook_scraper\__init__.py", line 221, in get_posts
    _scraper.login(*credentials)
  File "C:\Program Files\python3.9\lib\site-packages\facebook_scraper\facebook_scraper.py", line 966, in login
    response = self.submit_form(
  File "C:\Program Files\python3.9\lib\site-packages\facebook_scraper\facebook_scraper.py", line 951, in submit_form
    action = response.html.find("form", first=True).attrs.get('action')
AttributeError: 'NoneType' object has no attribute 'attrs'

**Comment by sumitpatel93** [comment]
you can use this - https://gist.github.com/sumitpatel93/364a3f512d77e14ee51fddd4fd0d2e68

there are errors due to old version of selenium
