### ISSUE TITLE
ImportError: lxml.html.clean module is now a separate project lxml_html_clean

### ISSUE THREAD

**Issue by escobar5** [kevinzg/facebook-scraper#1106]
I'm getting this error running facebook-scraper:

> Traceback (most recent call last):
>   File "/Users/escobar5/.local/bin/facebook-scraper", line 5, in <module>
>     from facebook_scraper.__main__ import run
>   File "/Users/escobar5/.local/pipx/venvs/facebook-scraper/lib/python3.12/site-packages/facebook_scraper/__init__.py", line 13, in <module>
>     from .facebook_scraper import FacebookScraper
>   File "/Users/escobar5/.local/pipx/venvs/facebook-scraper/lib/python3.12/site-packages/facebook_scraper/facebook_scraper.py", line 15, in <module>
>     from requests_html import HTMLSession
>   File "/Users/escobar5/.local/pipx/venvs/facebook-scraper/lib/python3.12/site-packages/requests_html.py", line 14, in <module>
>     from lxml.html.clean import Cleaner
>   File "/Users/escobar5/.local/pipx/venvs/facebook-scraper/lib/python3.12/site-packages/lxml/html/clean.py", line 18, in <module>
>     raise ImportError(
> ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
> Install lxml[html_clean] or lxml_html_clean directly.

Python 3.12.4

**Comment by BinhPQ2** [comment]
Try to

`pip install lxml_html_clean `

It might do the trick. This worked for me
