### ISSUE TITLE
Error thrown when scraping more than 20 post

### ISSUE THREAD

**Issue by mdunn85** [kevinzg/facebook-scraper#125]
If I try to scrape more than 20 posts from SamsungUk with extra info I get the following error

```Traceback (most recent call last):
  File "./scrape_site.py", line 13, in <module>
    get_posts()
  File "./scrape_site.py", line 8, in get_posts
    extra_info=True, page_limit=20
  File "./__init__.py", line 88, in write_posts_to_csv
    list_of_posts = list(get_posts(account=account, group=group, **kwargs))
  File "./facebook_scraper.py", line 95, in _generic_get_posts
    for i, page in zip(counter, iter_pages_fn()):
  File "./page_iterators.py", line 30, in generic_iter_pages
    response = request_fn(next_url)
  File "./facebook_scraper.py", line 58, in get
    response.raise_for_status()
  File "./bin/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://m.facebook.com/page_content_list_view/more/?page_id=126761694007536&start_cursor=%7B%22timeline_cursor%22%3A%22AQHRf8RuhKoLTyUoVMmS4UzbB2dBFFo9sb1QZCwrObcS3BltlK4K2A5dmouhaDbgMBxH-6agbPxDXR23F1fXLD_zI-_sMLN43hstyGEo2L0c1Osvj2YPHnY81e_sq1orxhSe%22%2C%22timeline_section_cursor%22%3Anull%2C%22has_next_page%22%3Atrue%7D&num_to_fetch=4&surface_type=posts_tab

**Comment by mdunn85** [comment]
I have scraped 10 other pages and not received this error

**Comment by neon-ninja** [comment]
```python
print(len(list(get_posts("SamsungUk", extra_info=True, page_limit=20, cookies="cookies.txt"))))
```
returns 77, so this seems fixed.
