### ISSUE TITLE
UnicodeEncodeError in reading few pages

### ISSUE THREAD

**Issue by ShikhaSingh10** [kevinzg/facebook-scraper#133]
On running the code over the page of TheBoysTV, faced this issue:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\shinu\facebook_crawler\facebook_venv\Scripts\facebook-scraper.exe\__main__.py", line 7, in <module>
  File "c:\users\shinu\facebook_crawler\facebook_venv\lib\site-packages\facebook_scraper\__main__.py", line 33, in run
    write_posts_to_csv(**kwargs, filename=args.filename, pages=args.pages, encoding=args.encoding)
  File "c:\users\shinu\facebook_crawler\facebook_venv\lib\site-packages\facebook_scraper\__init__.py", line 103, in write_posts_to_csv
    dict_writer.writerows(list_of_posts)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\csv.py", line 158, in writerows
    return self.writer.writerows(map(self._dict_to_list, rowdicts))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f974' in position 96: character maps to <undefined>

**Comment by kevinzg** [comment]
Try with `--encoding utf-8`.
