### ISSUE TITLE
CLI usage for .csv generation

### ISSUE THREAD

**Issue by gonzalo-gongora** [kevinzg/facebook-scraper#140]
The CLI are acting up at least when I use them in Windows Powershell. They used to work two days ago but now I get these messages when I try to generate a .csv file from any given facebok page:

```
PS C:\Users\steve> python -m facebook_scraper -f peepeepoopoo.csv -p 4 upaep
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\steve\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\facebook_scraper\__main__.py", line 55, in <module>
    run()
  File "C:\Users\steve\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\facebook_scraper\__main__.py", line 45, in run
    write_posts_to_csv(
  File "C:\Users\steve\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\facebook_scraper\__init__.py", line 140, in write_posts_to_csv
    dict_writer.writerows(list_of_posts)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\csv.py", line 157, in writerows
    return self.writer.writerows(map(self._dict_to_list, rowdicts))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f973' in position 45: character maps to <undefined>
```

Note: When I try to use:
                                      `python -m **facebook-scraper** -f peepeepoopoo.csv -p 4 upaep`

I get the following message:

`C:\Users\steve\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe: can't find '__main__' module in 'facebook-scraper'`

**Comment by kevinzg** [comment]
To solve the first error try adding `--encoding utf-8`.
For the second the correct name of the module is `facebook_scraper`, with an underscore instead of a hyphen.

**Comment by gonzalo-gongora** [comment]
Aye my man, thanks so much for the help. Just a little heads up, in the "Read Me" the 'CLI Usage' says the command line is: 

`$ facebook-scraper --filename nintendo_page_posts.csv --pages 1 nintendo` , with a hyphen.

**Comment by kevinzg** [comment]
Yeah, I guess that's confusing.

When you install `facebook-scraper` with pip it creates a `facebook-scraper` executable inside the bin directory of Python or the virtualenv. Maybe called `facebook-scraper.exe` on Windows, not sure. This name I chose and it's defined in the `pyproject.toml` file:

https://github.com/kevinzg/facebook-scraper/blob/b06bc43240537e3095059d4aad95b0290adc9dc7/pyproject.toml#L25-L26

And a different way to execute it is running the module as a script, with `python -m facebook_scraper`. This name must be the name of the module.

Hope that makes it clearer.
