### ISSUE TITLE
how to implement the correct way to Proxies

### ISSUE THREAD

**Issue by ferdinandtjandra** [kevinzg/facebook-scraper#141]
Hi all, i need help. i already tried set the proxies base on this issue #65  but it doesn't works. no i use version = "0.2.17".. what i've done is this 

i modified file facebook_scraper.py. become like this

`
def __init__(self, session=None, requests_kwargs=None):
        if session is None:
            session = HTMLSession()
            session.headers.update(self.default_headers)

        if requests_kwargs is None:
            requests_kwargs = {
                                'http': 'http://myProxyLink',
                                'https': 'http://myProxyLink'
                    }

        self.session = session
        self.requests_kwargs = requests_kwargs
`

and when i exec this command `facebook-scraper --filename nintendo_page_posts.csv --pages 1 nintendo`

display this error
`
Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/facebook-scraper", line 11, in <module>
sys.exit(run())
  File "/home/ec2-user/.local/lib/python3.7/site-packages/facebook_scraper/__main__.py", line 50, in run
    dump_location=args.dump_location,
  File "/home/ec2-user/.local/lib/python3.7/site-packages/facebook_scraper/__init__.py", line 101, in write_posts_to_csv
    get_posts(account=account, group=group, remove_source=not bool(dump_location), **kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/facebook_scraper/facebook_scraper.py", line 103, in _generic_get_posts
    for i, page in zip(counter, iter_pages_fn()):
  File "/home/ec2-user/.local/lib/python3.7/site-packages/facebook_scraper/page_iterators.py", line 30, in generic_iter_pages
    response = request_fn(next_url)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/facebook_scraper/facebook_scraper.py", line 60, in get
    response = self.session.get(url=url, **self.requests_kwargs, **kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
TypeError: request() got an unexpected keyword argument 'http'
`

sorry if preview code is bid messy. how do i can implement this proxies? please help

**Comment by kevinzg** [comment]
I believe the right argument is `proxies`, as in:
```python
requests_kwargs = {
    'proxies': {
        'http': 'http://myProxyLink',
        'https': 'http://myProxyLink'
    }
}
```

**Comment by ferdinandtjandra** [comment]
Thank You very Much!!! it works!!..
