### ISSUE TITLE
encode() argument 1 must be str, not None

### ISSUE THREAD

**Issue by wtyname** [kevinzg/facebook-scraper#189]
URL: https://m.facebook.com/SCHuangLawyer/posts/

Logs: 
C:\Users\admin\AppData\Local\Programs\Python\Python38\python.exe D:/workspace/untitled/test.py
Starting to iterate pages
Requesting page from: https://m.facebook.com/SCHuangLawyer/posts/
Parsing page response
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\requests_html.py", line 160, in lxml
    self._lxml = soup_parse(self.html, features='html.parser')
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\lxml\html\soupparser.py", line 33, in fromstring
    return _parse(data, beautifulsoup, makeelement, **bsargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\lxml\html\soupparser.py", line 79, in _parse
    root = _convert_tree(tree, makeelement)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\lxml\html\soupparser.py", line 152, in _convert_tree
    res_root = convert_node(html_root)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\lxml\html\soupparser.py", line 216, in convert_node
    return handler(bs_node, parent)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\lxml\html\soupparser.py", line 255, in convert_tag
    handler(child, res)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\lxml\html\soupparser.py", line 255, in convert_tag
    handler(child, res)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\lxml\html\soupparser.py", line 242, in convert_tag
    res = etree.SubElement(parent, bs_node.name, attrib=attribs)
  File "src\lxml\etree.pyx", line 3135, in lxml.etree.SubElement
  File "src\lxml\apihelpers.pxi", line 199, in lxml.etree._makeSubElement
  File "src\lxml\apihelpers.pxi", line 194, in lxml.etree._makeSubElement
  File "src\lxml\apihelpers.pxi", line 323, in lxml.etree._initNodeAttributes
  File "src\lxml\apihelpers.pxi", line 334, in lxml.etree._addAttributeToNode
  File "src\lxml\apihelpers.pxi", line 1527, in lxml.etree._utf8
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/workspace/untitled/test.py", line 23, in <module>
    posts = list(get_posts("SCHuangLawyer"))
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\facebook_scraper\facebook_scraper.py", line 122, in _generic_get_posts
    for i, page in zip(counter, iter_pages_fn()):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\facebook_scraper\page_iterators.py", line 41, in generic_iter_pages
    page = parser.get_page()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\facebook_scraper\page_iterators.py", line 79, in get_page
    raw_posts = raw_page.find(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\requests_html.py", line 212, in find
    for found in self.pq(selector)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\requests_html.py", line 149, in pq
    self._pq = PyQuery(self.lxml)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\requests_html.py", line 162, in lxml
    self._lxml = lxml.html.fromstring(self.raw_html)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\requests_html.py", line 97, in raw_html
    return etree.tostring(self.element, encoding='unicode').strip().encode(self.encoding)
TypeError: encode() argument 'encoding' must be str, not None

Process finished with exit code 1

**Comment by neon-ninja** [comment]
This error appears to be caused by the encoding information being dropped when regenerating the HTML element. This PR should fix it https://github.com/kevinzg/facebook-scraper/pull/191. Though it looks like the first few posts have encoding issues in the text.

Result:

```python
[{'available': True,
  'comments': 200,
  'comments_full': None,
  'factcheck': None,
  'image': 'https://scontent.fakl1-3.fna.fbcdn.net/v/t1.0-9/fr/cp0/e15/q65/104496505_571910773391168_6772605464033032372_o.jpg?_nc_cat=108&ccb=1-3&_nc_sid=8024bb&_nc_ohc=03HV4I59Hr4AX8fE2MR&_nc_oc=AQmbYUTyFHMj9KPgC0JGhoYSwzCUsDmLSOnlbVj8JfxaAj2mznRJswfsqN9blfh7NJ0&_nc_ht=scontent.fakl1-3.fna&tp=14&oh=619d7d98b275c6a75cf6fb4649cd03e5&oe=608804D1',
  'images': ['https://scontent.fakl1-3.fna.fbcdn.net/v/t1.0-9/fr/cp0/e15/q65/104496505_571910773391168_6772605464033032372_o.jpg?_nc_cat=108&ccb=1-3&_nc_sid=8024bb&_nc_ohc=03HV4I59Hr4AX8fE2MR&_nc_oc=AQmbYUTyFHMj9KPgC0JGhoYSwzCUsDmLSOnlbVj8JfxaAj2mznRJswfsqN9blfh7NJ0&_nc_ht=scontent.fakl1-3.fna&tp=14&oh=619d7d98b275c6a75cf6fb4649cd03e5&oe=608804D1'],
  'is_live': False,
  'likes': 880,
  'link': None,
  'post_id': '520599731855606',
  'post_text': '#å¤§å\x9c\x92 #è§\x80é\x9f³ #æ\x96°å±\x8b #æ¥\x8aæ¢\x85'
               ' '
               'ä¸\x96æ\x9d°ç\x9a\x86è¨\xadæ\x9c\x89æ\x9c\x8då\x8b\x99è\x99\x95ï¼\x8cæ\xad¡è¿\x8eé\x84\x89è¦ªæ\x9c\x89ç©ºä¾\x86å\x9d\x90ï¼\x81\n'
               '\n'
               'ï¼\x83æ³\x95å¾\x8bè«®è©¢ ï¼\x83æ\x9c\x8då\x8b\x99é\x84\x89è¦ª '
               'ï¼\x83ä¸\x96æ\x9d°ç\x94¨å¿\x83\n'
               '\n'
               'ã\x80\x90å¤§å\x9c\x92æ\x9c\x8då\x8b\x99è\x99\x95ã\x80\x91\n'
               'å\x9c°å\x9d\x80ï¼\x9aæ¡\x83å\x9c\x92å¸\x82å¤§å\x9c\x92å\x8d\x80ä¸\xadå±±å\x8c\x97è·¯159è\x99\x9f\n'
               'é\x9b»è©±ï¼\x9a0972-591608\n'
               'æ³\x95å¾\x8bè«®è©¢æ\x9c\x8då\x8b\x99æ\x99\x82é\x96\x93ï¼\x9aæ¯\x8fé\x80±äº\x94æ\x99\x9aä¸\x8a7~9é»\x9e '
               '(è«\x8bå\x85'
               '\x88é\xa0\x90ç´\x84)\n'
               'è\x88ªç©ºå\x9f\x8eå\x9c\x9få\x9c°å¾µæ\x94¶ä»£æ\x9b¸è«®è©¢æ\x9c\x8då\x8b\x99ï¼\x9aæ¯\x8fé\x80±äº\x94ï¼\x88ä¸\x8aå\x8d\x889:30-12:00ï¼\x8cä¸\x8bå\x8d\x88 '
               '14:00-17:00ï¼\x89\n'
               '\n'
               'ã\x80\x90è§\x80é\x9f³æ\x9c\x8då\x8b\x99è\x99\x95ã\x80\x91\n'
               'å\x9c°å\x9d\x80ï¼\x9aæ¡\x83å\x9c\x92å¸\x82è§\x80é\x9f³å\x8d\x80ä¸\xadå±±è·¯äº\x8cæ®µ595è\x99\x9f\n'
               'é\x9b»è©±ï¼\x9a0972-591607\n'
               'æ³\x95å¾\x8bè«®è©¢æ\x9c\x8då\x8b\x99æ\x99\x82é\x96\x93ï¼\x9aæ¯\x8fé\x80±ä¸\x80 '
               'æ\x99\x9aä¸\x8a7~9é»\x9e (è«\x8bå\x85'
               '\x88é\xa0\x90ç´\x84)\n'
               '\n'
               'ã\x80\x90æ\x96°å±\x8bæ\x9c\x8då\x8b\x99è\x99\x95ã\x80\x91\n'
               'å\x9c°å\x9d\x80ï¼\x9aæ¡\x83å\x9c\x92å¸\x82æ\x96°å±\x8bå\x8d\x80ä¸\xadè\x8f¯è·¯237è\x99\x9f\n'
               'é\x9b»è©±ï¼\x9a0972-591606\n'
               'æ³\x95å¾\x8bè«®è©¢æ\x9c\x8då\x8b\x99æ\x99\x82é\x96\x93ï¼\x9aæ¯\x8fé\x80±äº\x94 '
               'ä¸\x8bå\x8d\x881~3é»\x9e (è«\x8bå\x85'
               '\x88é\xa0\x90ç´\x84)\n'
               '\n'
               'ã\x80\x90æ¥\x8aæ¢\x85'
               'æ\x9c\x8då\x8b\x99è\x99\x95ã\x80\x91\n'
               'å\x9c°å\x9d\x80ï¼\x9aæ¡\x83å\x9c\x92å¸\x82æ¥\x8aæ¢\x85'
               'å\x8d\x80è\x87ªç«\x8bè¡\x97299è\x99\x9f\n'
               'é\x9b»è©±ï¼\x9a0972-591605\n'
               'æ³\x95å¾\x8bè«®è©¢æ\x9c\x8då\x8b\x99æ\x99\x82é\x96\x93ï¼\x9aæ¯\x8fé\x80±äº\x8c '
               'æ\x99\x9aä¸\x8a7~9é»\x9eã\x80\x81æ¯\x8fé\x80±å\x9b\x9b '
               'ä¸\x8bå\x8d\x882:30~4:30ï¼\x88è«\x8bå\x85'
               '\x88é\xa0\x90ç´\x84)\n'
               '\n'
               'ï¼\x83ç«\x8bæ³\x95å§\x94å\x93¡é»\x83ä¸\x96æ\x9d° '
               'ï¼\x83æ¡\x83å\x9c\x92é\x80²æ\xad¥',
  'post_url': 'https://facebook.com/SCHuangLawyer/posts/520599731855606',
  'shared_post_id': None,
  'shared_post_url': None,
  'shared_text': '',
  'shared_time': None,
  'shared_user_id': None,
  'shared_username': None,
  'shares': 0,
  'text': '#å¤§å\x9c\x92 #è§\x80é\x9f³ #æ\x96°å±\x8b #æ¥\x8aæ¢\x85'
          ' '
          'ä¸\x96æ\x9d°ç\x9a\x86è¨\xadæ\x9c\x89æ\x9c\x8då\x8b\x99è\x99\x95ï¼\x8cæ\xad¡è¿\x8eé\x84\x89è¦ªæ\x9c\x89ç©ºä¾\x86å\x9d\x90ï¼\x81\n'
          '\n'
          'ï¼\x83æ³\x95å¾\x8bè«®è©¢ ï¼\x83æ\x9c\x8då\x8b\x99é\x84\x89è¦ª '
          'ï¼\x83ä¸\x96æ\x9d°ç\x94¨å¿\x83\n'
          '\n'
          'ã\x80\x90å¤§å\x9c\x92æ\x9c\x8då\x8b\x99è\x99\x95ã\x80\x91\n'
          'å\x9c°å\x9d\x80ï¼\x9aæ¡\x83å\x9c\x92å¸\x82å¤§å\x9c\x92å\x8d\x80ä¸\xadå±±å\x8c\x97è·¯159è\x99\x9f\n'
          'é\x9b»è©±ï¼\x9a0972-591608\n'
          'æ³\x95å¾\x8bè«®è©¢æ\x9c\x8då\x8b\x99æ\x99\x82é\x96\x93ï¼\x9aæ¯\x8fé\x80±äº\x94æ\x99\x9aä¸\x8a7~9é»\x9e '
          '(è«\x8bå\x85'
          '\x88é\xa0\x90ç´\x84)\n'
          'è\x88ªç©ºå\x9f\x8eå\x9c\x9få\x9c°å¾µæ\x94¶ä»£æ\x9b¸è«®è©¢æ\x9c\x8då\x8b\x99ï¼\x9aæ¯\x8fé\x80±äº\x94ï¼\x88ä¸\x8aå\x8d\x889:30-12:00ï¼\x8cä¸\x8bå\x8d\x88 '
          '14:00-17:00ï¼\x89\n'
          '\n'
          'ã\x80\x90è§\x80é\x9f³æ\x9c\x8då\x8b\x99è\x99\x95ã\x80\x91\n'
          'å\x9c°å\x9d\x80ï¼\x9aæ¡\x83å\x9c\x92å¸\x82è§\x80é\x9f³å\x8d\x80ä¸\xadå±±è·¯äº\x8cæ®µ595è\x99\x9f\n'
          'é\x9b»è©±ï¼\x9a0972-591607\n'
          'æ³\x95å¾\x8bè«®è©¢æ\x9c\x8då\x8b\x99æ\x99\x82é\x96\x93ï¼\x9aæ¯\x8fé\x80±ä¸\x80 '
          'æ\x99\x9aä¸\x8a7~9é»\x9e (è«\x8bå\x85'
          '\x88é\xa0\x90ç´\x84)\n'
          '\n'
          'ã\x80\x90æ\x96°å±\x8bæ\x9c\x8då\x8b\x99è\x99\x95ã\x80\x91\n'
          'å\x9c°å\x9d\x80ï¼\x9aæ¡\x83å\x9c\x92å¸\x82æ\x96°å±\x8bå\x8d\x80ä¸\xadè\x8f¯è·¯237è\x99\x9f\n'
          'é\x9b»è©±ï¼\x9a0972-591606\n'
          'æ³\x95å¾\x8bè«®è©¢æ\x9c\x8då\x8b\x99æ\x99\x82é\x96\x93ï¼\x9aæ¯\x8fé\x80±äº\x94 '
          'ä¸\x8bå\x8d\x881~3é»\x9e (è«\x8bå\x85'
          '\x88é\xa0\x90ç´\x84)\n'
          '\n'
          'ã\x80\x90æ¥\x8aæ¢\x85'
          'æ\x9c\x8då\x8b\x99è\x99\x95ã\x80\x91\n'
          'å\x9c°å\x9d\x80ï¼\x9aæ¡\x83å\x9c\x92å¸\x82æ¥\x8aæ¢\x85'
          'å\x8d\x80è\x87ªç«\x8bè¡\x97299è\x99\x9f\n'
          'é\x9b»è©±ï¼\x9a0972-591605\n'
          'æ³\x95å¾\x8bè«®è©¢æ\x9c\x8då\x8b\x99æ\x99\x82é\x96\x93ï¼\x9aæ¯\x8fé\x80±äº\x8c '
          'æ\x99\x9aä¸\x8a7~9é»\x9eã\x80\x81æ¯\x8fé\x80±å\x9b\x9b '
          'ä¸\x8bå\x8d\x882:30~4:30ï¼\x88è«\x8bå\x85'
          '\x88é\xa0\x90ç´\x84)\n'
          '\n'
          'ï¼\x83ç«\x8bæ³\x95å§\x94å\x93¡é»\x83ä¸\x96æ\x9d° '
          'ï¼\x83æ¡\x83å\x9c\x92é\x80²æ\xad¥',
  'time': datetime.datetime(2020, 3, 27, 0, 11),
  'user_id': '233645830550999',
  'username': 'é»\x83ä¸\x96æ\x9d°',
  'video': None,
  'video_id': None,
  'video_thumbnail': None},
 {'available': True,
  'comments': 4,
  'comments_full': None,
  'factcheck': None,
  'image': 'https://scontent.fakl1-3.fna.fbcdn.net/v/t1.0-9/fr/cp0/e15/q65/166269714_745976729317904_1603138741202310261_o.jpg?_nc_cat=111&ccb=1-3&_nc_sid=8024bb&_nc_ohc=VwlWtM1dJdcAX8Ua09u&_nc_ht=scontent.fakl1-3.fna&tp=14&oh=fd5b9dc30e388c0fc291ce8880054e38&oe=6087398E',
  'images': ['https://scontent.fakl1-3.fna.fbcdn.net/v/t1.0-9/fr/cp0/e15/q65/166269714_745976729317904_1603138741202310261_o.jpg?_nc_cat=111&ccb=1-3&_nc_sid=8024bb&_nc_ohc=VwlWtM1dJdcAX8Ua09u&_nc_ht=scontent.fakl1-3.fna&tp=14&oh=fd5b9dc30e388c0fc291ce8880054e38&oe=6087398E'],
  'is_live': False,
  'likes': 326,
  'link': None,
  'post_id': '745996059315971',
  'post_text': 'ä»\x8aå¤©ä¾\x86å\x88°è§\x80é\x9f³è¾²æ°\x91ç¯\x80å¤§æ\x9c\x83ï¼\x8cç\x8f¾å\xa0'
               '´ç\x8d²ç\x8d\x8eç\x9a\x84è¾²å\x8f\x8bæ\x9c\x89ä¸\x8då°\x91æ\x98¯é\x9d\x92è¾²ï¼\x8cé\x80\x99ä»£è¡¨è\x91\x97è¾²æ¥\xadç\x9a\x84ä¸\x96ä»£å\x82³æ\x89¿ï¼\x8cä¹\x9fä»£è¡¨è¾²æ¥\xadç\x9a\x84å¸\x8cæ\x9c\x9bï¼\x81æ\x9c\x9fç\x9b¼å¤§å®¶ä¸\x80èµ·ç¹¼çº\x8cæ\x94¯æ\x8c\x81æ\x88\x91å\x80\x91å\x9c¨å\x9c°ç\x9a\x84è¾²æ¥\xad~\n'
               '\n'
               '#ç«\x8bæ³\x95å§\x94å\x93¡é»\x83ä¸\x96æ\x9d°\n'
               '#è§\x80é\x9f³è¾²æ°\x91ç¯\x80 #è§\x80é\x9f³ #è¾²æ°\x91ç¯\x80',
  'post_url': 'https://facebook.com/SCHuangLawyer/posts/745996059315971',
  'shared_post_id': None,
  'shared_post_url': None,
  'shared_text': '',
  'shared_time': None,
  'shared_user_id': None,
  'shared_username': None,
  'shares': 0,
  'text': 'ä»\x8aå¤©ä¾\x86å\x88°è§\x80é\x9f³è¾²æ°\x91ç¯\x80å¤§æ\x9c\x83ï¼\x8cç\x8f¾å\xa0'
          '´ç\x8d²ç\x8d\x8eç\x9a\x84è¾²å\x8f\x8bæ\x9c\x89ä¸\x8då°\x91æ\x98¯é\x9d\x92è¾²ï¼\x8cé\x80\x99ä»£è¡¨è\x91\x97è¾²æ¥\xadç\x9a\x84ä¸\x96ä»£å\x82³æ\x89¿ï¼\x8cä¹\x9fä»£è¡¨è¾²æ¥\xadç\x9a\x84å¸\x8cæ\x9c\x9bï¼\x81æ\x9c\x9fç\x9b¼å¤§å®¶ä¸\x80èµ·ç¹¼çº\x8cæ\x94¯æ\x8c\x81æ\x88\x91å\x80\x91å\x9c¨å\x9c°ç\x9a\x84è¾²æ¥\xad~\n'
          '\n'
          '#ç«\x8bæ³\x95å§\x94å\x93¡é»\x83ä¸\x96æ\x9d°\n'
          '#è§\x80é\x9f³è¾²æ°\x91ç¯\x80 #è§\x80é\x9f³ #è¾²æ°\x91ç¯\x80',
  'time': datetime.datetime(2021, 3, 28, 17, 22, 58),
  'user_id': '233645830550999',
  'username': 'é»\x83ä¸\x96æ\x9d°',
  'video': None,
  'video_id': None,
  'video_thumbnail': None},
 {'available': True,
  'comments': 5,
  'comments_full': None,
  'factcheck': None,
  'image': 'https://scontent.fakl1-2.fna.fbcdn.net/v/t1.0-9/fr/cp0/e15/q65/163850208_745531712695739_444844965425232944_o.jpg?_nc_cat=101&ccb=1-3&_nc_sid=8024bb&_nc_ohc=v_u97efWZvkAX9bi3Wl&_nc_ht=scontent.fakl1-2.fna&tp=14&oh=b4f13884e731c93038be9c1d7ef740ca&oe=60879FDB',
  'images': ['https://scontent.fakl1-2.fna.fbcdn.net/v/t1.0-9/fr/cp0/e15/q65/163850208_745531712695739_444844965425232944_o.jpg?_nc_cat=101&ccb=1-3&_nc_sid=8024bb&_nc_ohc=v_u97efWZvkAX9bi3Wl&_nc_ht=scontent.fakl1-2.fna&tp=14&oh=b4f13884e731c93038be9c1d7ef740ca&oe=60879FDB',
             'https://scontent.fakl1-2.fna.fbcdn.net/v/t1.0-9/164064193_745533066028937_2402327484750811462_o.png?_nc_cat=100&ccb=1-3&_nc_sid=8024bb&_nc_ohc=JYk7r6cB7aAAX-nvn6c&_nc_ht=scontent.fakl1-2.fna&oh=c9b2e20c636863370f88056e67006b4c&oe=60887EEF'],
  'is_live': False,
  'likes': 273,
  'link': 'https://goo.gl/maps/SFzrNQQjKPX3mfGn9',
  'post_id': '745533119362265',
  'post_text': '還記得去年此時，COVID-19疫情升溫造成許多活動停辦，「#桃園彩色海芋季」就是受到波及的活動之一。靠著中央與全民的努力防疫，今年桃園彩色海芋季不缺席，今天3/27起至4/11在老地方─大園區聖德北路與田溪路交叉處廣達5.9公頃的範圍，以「#海洋奇芋季」為主題打造了繽紛的海洋樂園。\n'
               '\n'
               '歡迎全台的鄉親朋友蒞臨造訪！\n'
               '⚠️提醒您：配合防疫措施，活動會場請全程配戴口罩。\n'
               '\n'
               '◎活動期間交通管制，路肩禁止停車。請將車輛停妥後，轉乘免費區外接駁車（紅線）。\n'
               '\n'
               '◎3/27-4/11活動期間，假日07：00-18：00進行交通管制未出示通行證者，汽機車不得進入。\n'
               '\n'
               'GOOGLEMAP：https://goo.gl/maps/SFzrNQQjKPX3mfGn9\n'
               '\n'
               '官方網站：http://www.2021callalily.com.tw/h/Index?key=q8ka0\n'
               '官方活動FB：https://m.facebook.com/DAYUANFLOWER/\n'
               '\n'
               '#立法委員黃世杰',
  'post_url': 'https://facebook.com/SCHuangLawyer/posts/745533119362265',
  'shared_post_id': None,
  'shared_post_url': None,
  'shared_text': '',
  'shared_time': None,
  'shared_user_id': None,
  'shared_username': None,
  'shares': 0,
  'text': '還記得去年此時，COVID-19疫情升溫造成許多活動停辦，「#桃園彩色海芋季」就是受到波及的活動之一。靠著中央與全民的努力防疫，今年桃園彩色海芋季不缺席，今天3/27起至4/11在老地方─大園區聖德北路與田溪路交叉處廣達5.9公頃的範圍，以「#海洋奇芋季」為主題打造了繽紛的海洋樂園。\n'
          '\n'
          '歡迎全台的鄉親朋友蒞臨造訪！\n'
          '⚠️提醒您：配合防疫措施，活動會場請全程配戴口罩。\n'
          '\n'
          '◎活動期間交通管制，路肩禁止停車。請將車輛停妥後，轉乘免費區外接駁車（紅線）。\n'
          '\n'
          '◎3/27-4/11活動期間，假日07：00-18：00進行交通管制未出示通行證者，汽機車不得進入。\n'
          '\n'
          'GOOGLEMAP：https://goo.gl/maps/SFzrNQQjKPX3mfGn9\n'
          '\n'
          '官方網站：http://www.2021callalily.com.tw/h/Index?key=q8ka0\n'
          '官方活動FB：https://m.facebook.com/DAYUANFLOWER/\n'
          '\n'
          '#立法委員黃世杰',
  'time': datetime.datetime(2021, 3, 27, 20, 32, 40),
  'user_id': '233645830550999',
  'username': '黃世杰',
  'video': None,
  'video_id': None,
  'video_thumbnail': None},
 {'available': True,
  'comments': 5,
  'comments_full': None,
  'factcheck': None,
  'image': 'https://scontent.fakl1-3.fna.fbcdn.net/v/t1.0-9/fr/cp0/e15/q65/163650132_743489722899938_7093374187739732340_o.jpg?_nc_cat=108&ccb=1-3&_nc_sid=8024bb&_nc_ohc=glYxJV_FfnsAX9MFeo3&_nc_ht=scontent.fakl1-3.fna&tp=14&oh=f18009a5f26f69df8fb2558c6ffac7b4&oe=60886068',
  'images': ['https://scontent.fakl1-3.fna.fbcdn.net/v/t1.0-9/fr/cp0/e15/q65/163650132_743489722899938_7093374187739732340_o.jpg?_nc_cat=108&ccb=1-3&_nc_sid=8024bb&_nc_ohc=glYxJV_FfnsAX9MFeo3&_nc_ht=scontent.fakl1-3.fna&tp=14&oh=f18009a5f26f69df8fb2558c6ffac7b4&oe=60886068',
             'https://scontent.fakl1-3.fna.fbcdn.net/v/t1.0-9/fr/cp0/e15/q65/162842143_743489822899928_5829855272594656715_o.jpg?_nc_cat=111&ccb=1-3&_nc_sid=8024bb&_nc_ohc=wTkDuVlC55AAX91E7ZZ&_nc_ht=scontent.fakl1-3.fna&tp=14&oh=4d093c99ef233de0944525007c222780&oe=6084EC5E'],
  'is_live': False,
  'likes': 198,
  'link': None,
  'post_id': '743490822899828',
  'post_text': '除了為國軍與海巡弟兄加油，也要向第一線醫護人員致敬！感謝他們在COVID-19肆虐全球的疫情中，站在最前線守護全民的健康！\n'
               '\n'
               '應 #中華職棒會長 蔡其昌 之邀，世杰與眾嘉賓來到桃園球場參加樂天桃猿主場開幕賽，開球由 #福利部桃園醫院 院長 #徐永年 '
               '擔任打者，護理師葉佳燕擔任投手，桃園市長 鄭文燦 則擔任開球主審，接下來的防疫大作戰讓我們如同球隊一樣，全民一起努力！\n'
               '\n'
               '#中華職棒\n'
               '#樂天桃猿\n'
               '#樂天桃猿主場開幕\n'
               '#立法委員黃世杰\n'
               '#防疫\n'
               '#桃園加油 #台灣加油',
  'post_url': 'https://facebook.com/SCHuangLawyer/posts/743490822899828',
  'shared_post_id': None,
  'shared_post_url': None,
  'shared_text': '',
  'shared_time': None,
  'shared_user_id': None,
  'shared_username': None,
  'shares': 0,
  'text': '除了為國軍與海巡弟兄加油，也要向第一線醫護人員致敬！感謝他們在COVID-19肆虐全球的疫情中，站在最前線守護全民的健康！\n'
          '\n'
          '應 #中華職棒會長 蔡其昌 之邀，世杰與眾嘉賓來到桃園球場參加樂天桃猿主場開幕賽，開球由 #福利部桃園醫院 院長 #徐永年 '
          '擔任打者，護理師葉佳燕擔任投手，桃園市長 鄭文燦 則擔任開球主審，接下來的防疫大作戰讓我們如同球隊一樣，全民一起努力！\n'
          '\n'
          '#中華職棒\n'
          '#樂天桃猿\n'
          '#樂天桃猿主場開幕\n'
          '#立法委員黃世杰\n'
          '#防疫\n'
          '#桃園加油 #台灣加油',
  'time': datetime.datetime(2021, 3, 24, 13, 13),
  'user_id': '233645830550999',
  'username': '黃世杰',
  'video': None,
  'video_id': None,
  'video_thumbnail': None},
 {'available': True,
  'comments': 5,
  'comments_full': None,
  'factcheck': None,
  'image': 'https://scontent.fakl1-3.fna.fbcdn.net/v/t1.0-9/fr/cp0/e15/q65/162352475_743407962908114_4541182572147347793_o.jpg?_nc_cat=108&ccb=1-3&_nc_sid=8024bb&_nc_ohc=CAyXXyLGf-4AX_7Itq3&_nc_ht=scontent.fakl1-3.fna&tp=14&oh=0b5f22dad768a697bebd50d280d29b3f&oe=6087EAFE',
  'images': ['https://scontent.fakl1-3.fna.fbcdn.net/v/t1.0-9/fr/cp0/e15/q65/162352475_743407962908114_4541182572147347793_o.jpg?_nc_cat=108&ccb=1-3&_nc_sid=8024bb&_nc_ohc=CAyXXyLGf-4AX_7Itq3&_nc_ht=scontent.fakl1-3.fna&tp=14&oh=0b5f22dad768a697bebd50d280d29b3f&oe=6087EAFE',
             'https://scontent.fakl1-3.fna.fbcdn.net/v/t1.0-9/fr/cp0/e15/q65/161916780_743407902908120_2338483083460746789_o.jpg?_nc_cat=103&ccb=1-3&_nc_sid=8024bb&_nc_ohc=ILgt8oAiPx0AX8XTWli&_nc_ht=scontent.fakl1-3.fna&tp=14&oh=203af94a832011b69783d0de8d837e0a&oe=6088070C',
             'https://scontent.fakl1-2.fna.fbcdn.net/v/t1.0-9/fr/cp0/e15/q65/162765948_743413662907544_5192849973647518733_o.jpg?_nc_cat=104&ccb=1-3&_nc_sid=8024bb&_nc_ohc=mc-0LtDF1wEAX-1Y168&_nc_ht=scontent.fakl1-2.fna&tp=14&oh=5e66840a4869030e58aac26fb9067aad&oe=60861968'],
  'is_live': False,
  'likes': 481,
  'link': None,
  'post_id': '743419976240246',
  'post_text': '今年過年，桃園市政府為了防疫將春節勞軍活動延期，但是 #桃園市長 鄭文燦 與 '
               '世杰沒有忘記保家衛國的三軍將士與海巡官兵，今天來到海巡署北部分署(忠愛莊)慰勞辛苦的戰士們。\n'
               '\n'
               '市長 #鄭文燦 '
               '與世杰在勞軍的同時，也惦記著台東的F-5E飛行員與參與搜救的軍方與海巡弟兄們，希望能盡速找到另一名飛行員，也盼逝者安息，市長鄭文燦與世杰向辛苦的國軍與海巡弟兄致上最深的敬意。\n'
               '\n'
               '#立法委員黃世杰\n'
               '#春節勞軍 #勞軍\n'
               '#向國軍致敬',
  'post_url': 'https://facebook.com/SCHuangLawyer/posts/743419976240246',
  'shared_post_id': None,
  'shared_post_url': None,
  'shared_text': '',
  'shared_time': None,
  'shared_user_id': None,
  'shared_username': None,
  'shares': 0,
  'text': '今年過年，桃園市政府為了防疫將春節勞軍活動延期，但是 #桃園市長 鄭文燦 與 '
          '世杰沒有忘記保家衛國的三軍將士與海巡官兵，今天來到海巡署北部分署(忠愛莊)慰勞辛苦的戰士們。\n'
          '\n'
          '市長 #鄭文燦 '
          '與世杰在勞軍的同時，也惦記著台東的F-5E飛行員與參與搜救的軍方與海巡弟兄們，希望能盡速找到另一名飛行員，也盼逝者安息，市長鄭文燦與世杰向辛苦的國軍與海巡弟兄致上最深的敬意。\n'
          '\n'
          '#立法委員黃世杰\n'
          '#春節勞軍 #勞軍\n'
          '#向國軍致敬',
  'time': datetime.datetime(2021, 3, 23, 23, 46, 40),
  'user_id': '233645830550999',
  'username': '黃世杰',
  'video': None,
  'video_id': None,
  'video_thumbnail': None},
 {'available': True,
  'comments': 7,
  'comments_full': None,
  'factcheck': None,
  'image': None,
  'is_live': False,
  'likes': 230,
  'link': 'https://water.taiwanstat.com/',
  'post_id': '742955499620027',
  'post_text': '今天是 #世界水資源日 ，雖然雨下了一整天，似乎為桃園解了些許乾渴，但是世杰依然為水情感到憂心，實際上我們桃園 #石門水庫 '
               '的蓄水率也只剩40.9%，需同時供給新北、桃園、新竹的民生、農業與工業用水，其實水情相當吃緊，許多灌區也以停灌因應，在民生與工業方面，也需要新北、桃園、新竹的鄉親一起惜水、節水，一起度過這次極端的旱象。\n'
               '\n'
               '台灣水庫即時水情↓\n'
               'https://water.taiwanstat.com/\n'
               '\n'
               '#立法委員黃世杰\n'
               '#乾旱 #缺水 #省水大作戰 #節水',
  'post_url': 'https://facebook.com/SCHuangLawyer/videos/590077211948740',
  'shared_post_id': None,
  'shared_post_url': None,
  'shared_text': '',
  'shared_time': None,
  'shared_user_id': None,
  'shared_username': None,
  'shares': 0,
  'text': '今天是 #世界水資源日 ，雖然雨下了一整天，似乎為桃園解了些許乾渴，但是世杰依然為水情感到憂心，實際上我們桃園 #石門水庫 '
          '的蓄水率也只剩40.9%，需同時供給新北、桃園、新竹的民生、農業與工業用水，其實水情相當吃緊，許多灌區也以停灌因應，在民生與工業方面，也需要新北、桃園、新竹的鄉親一起惜水、節水，一起度過這次極端的旱象。\n'
          '\n'
          '台灣水庫即時水情↓\n'
          'https://water.taiwanstat.com/\n'
          '\n'
          '#立法委員黃世杰\n'
          '#乾旱 #缺水 #省水大作戰 #節水',
  'time': datetime.datetime(2021, 3, 23, 1, 13),
  'user_id': '233645830550999',
  'username': '黃世杰',
  'video': 'https://video.fakl1-3.fna.fbcdn.net/v/t42.1790-2/163558564_174397004518194_4569334011310093894_n.mp4?_nc_cat=107&ccb=1-3&_nc_sid=985c63&efg=eyJ2ZW5jb2RlX3RhZyI6InN2ZV9zZCJ9&_nc_ohc=jV5v9TI-cqYAX9k08jk&_nc_ht=video.fakl1-3.fna&oh=a8e45a9d693aaf53d9150a68a59ecb7c&oe=60615F76',
  'video_id': '590077211948740',
  'video_thumbnail': 'https://scontent.fakl1-2.fna.fbcdn.net/v/t15.5256-10/cp0/e15/q65/s320x320/154786880_590085625281232_4948188827635230228_n.jpg?_nc_cat=109&ccb=1-3&_nc_sid=ccf8b3&_nc_ohc=lOJk1wQ9UIYAX-0D3jy&_nc_ht=scontent.fakl1-2.fna&tp=9&oh=41ce3308ebcb8271618286499471e4ae&oe=6084EBBC'}]
```
