### ISSUE TITLE
 dict contains fields not in fieldnames: 'images'

### ISSUE THREAD

**Issue by wgicio** [kevinzg/facebook-scraper#192]
macca@macca:~/Documents$ facebook-scraper --filename 1523008504577896.csv --pages 15 1523008504577896
Traceback (most recent call last):
  File "/usr/local/bin/facebook-scraper", line 8, in <module>
    sys.exit(run())
  File "/home/macca/.local/lib/python3.8/site-packages/facebook_scraper/__main__.py", line 45, in run
    write_posts_to_csv(
  File "/home/macca/.local/lib/python3.8/site-packages/facebook_scraper/__init__.py", line 165, in write_posts_to_csv
    dict_writer.writerows(list_of_posts)
  File "/usr/lib/python3.8/csv.py", line 157, in writerows
    return self.writer.writerows(map(self._dict_to_list, rowdicts))
  File "/usr/lib/python3.8/csv.py", line 149, in _dict_to_list
    raise ValueError("dict contains fields not in fieldnames: "
ValueError: dict contains fields not in fieldnames: 'images'

**Comment by neon-ninja** [comment]
What version are you using?

**Comment by wgicio** [comment]
facebook-scraper         0.2.26

**Comment by neon-ninja** [comment]
Does the script still generate a CSV despite the error? If so, can you post its contents here?

**Comment by kevinzg** [comment]
The CSV writer function uses the first post to get the columns to use as headers, and `images` is not always set. Adding `images` to the make new post function should fix this problem.

**Comment by neon-ninja** [comment]
I see - here's a PR for that https://github.com/kevinzg/facebook-scraper/pull/193/files
