### ISSUE TITLE
Proxy setting in kwargs [issue]

### ISSUE THREAD

**Issue by fashandatafields** [kevinzg/facebook-scraper#241]
`Traceback (most recent call last):
  File "/Users/fashaan/Documents/datafields_development/datafields_social/django_facebook/lib/python3.7/site-packages/requests/adapters.py", line 412, in send
    conn = self.get_connection(request.url, proxies)
  File "/Users/fashaan/Documents/datafields_development/datafields_social/django_facebook/lib/python3.7/site-packages/requests/adapters.py", line 309, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "/Users/fashaan/Documents/datafields_development/datafields_social/django_facebook/lib/python3.7/site-packages/requests/adapters.py", line 199, in proxy_manager_for
    **proxy_kwargs)
  File "/Users/fashaan/Documents/datafields_development/datafields_social/django_facebook/lib/python3.7/site-packages/urllib3/poolmanager.py", line 536, in proxy_from_url
    return ProxyManager(proxy_url=url, **kw)
  File "/Users/fashaan/Documents/datafields_development/datafields_social/django_facebook/lib/python3.7/site-packages/urllib3/poolmanager.py", line 480, in __init__
    raise ProxySchemeUnknown(proxy.scheme)
urllib3.exceptions.ProxySchemeUnknown: Proxy URL had unsupported scheme infojk, should use http:// or https://

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "facebookscraper/__main__.py", line 57, in <module>
    run()
  File "facebookscraper/__main__.py", line 50, in run
    fbwrapper.scrape_post(forum, int(no_of_page))
  File "/Users/fashaan/Documents/datafields_development/datafields_social/facebook_project/facebookscraper/fb_wrapper.py", line 48, in scrape_post
    posts = list(get_posts(post_urls=["https://m.facebook.com/story.php?story_fbid=473186744004675&id=1732816076985345"], timeout=60, cookies=set_cookie, options={'comments': True, 'reactors': True}))
  File "/Users/fashaan/Documents/datafields_development/datafields_social/django_facebook/lib/python3.7/site-packages/facebook_scraper/facebook_scraper.py", line 65, in get_posts_by_url
    response = self.get(post_url)
  File "/Users/fashaan/Documents/datafields_development/datafields_social/django_facebook/lib/python3.7/site-packages/facebook_scraper/facebook_scraper.py", line 196, in get
    response = self.session.get(url=url, **self.requests_kwargs, **kwargs)
  File "/Users/fashaan/Documents/datafields_development/datafields_social/django_facebook/lib/python3.7/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/Users/fashaan/Documents/datafields_development/datafields_social/django_facebook/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/fashaan/Documents/datafields_development/datafields_social/django_facebook/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/fashaan/Documents/datafields_development/datafields_social/django_facebook/lib/python3.7/site-packages/requests/adapters.py", line 414, in send
    raise InvalidURL(e, request=request)
requests.exceptions.InvalidURL: Proxy URL had unsupported scheme infojk, should use http:// or https://
`

**Comment by fashandatafields** [comment]
please @neon-ninja

**Comment by fashandatafields** [comment]
```
proxy_value = {'proxies':{'http':proxy, 'https': proxy}}
self.requests_kwargs.update(proxy_value)
```
Gives error in new update

**Comment by neon-ninja** [comment]
as it says, make sure your proxy url starts with http:// or https://

**Comment by fashandatafields** [comment]
@neon-ninja I need to clarify one thing.
Even we get cookies from chrome and set them in the project while getting post. Will Facebook ban us.

does facebook-scraper use a different browser (firefox) and access Facebook?

**Comment by neon-ninja** [comment]
So far, I've only seen Facebook issue temporary (~1h) bans for excessive scraping. facebook-scraper makes requests using the python requests library, so directly from Python. It is not dependent on any browser.

**Comment by fashandatafields** [comment]
@neon-ninja how does the facebook-scraper render js. Is it using a browser

**Comment by fashandatafields** [comment]
@neon-ninja may i know about this
 ```
Warning: the first time you run this method, it will download
  583:         Chromium into your home directory (``~/.pyppeteer``).
  584          """
```

**Comment by neon-ninja** [comment]
The underlying requests-html library does support rendering JS (https://docs.python-requests.org/projects/requests-html/en/latest/#javascript-support), but I don't think facebook-scraper uses this feature

**Comment by fashandatafields** [comment]
Ok, so facebook-scraper is using chromium browser right? @neon-ninja

**Comment by neon-ninja** [comment]
No, facebook-scraper doesn't use render(), and so doesn't use chromium

**Comment by fashandatafields** [comment]
thanks @neon-ninja
