### ISSUE TITLE
login in Facebook

### ISSUE THREAD

**Issue by mpizosdim** [kevinzg/facebook-scraper#262]
I am trying to login to facebook to get posts from private posts and tried: 

```
from facebook_scraper.utils import parse_cookie_file
from facebook_scraper import FacebookScraper

scraper = FacebookScraper()
scraper.session.cookies = parse_cookie_file('cookies.json')
scraper.is_logged_in() == True # Should be true but is False
```

and
```
from facebook_scraper import FacebookScraper

scraper = FacebookScraper()
scraper.login(email='username@protonmail.com', password='apassword')
scraper.is_logged_in() == True # Should be true but is False
```

But both fail to login. Any reason or other way of successfully login? 

version `facebook-scraper==0.2.36`

**Comment by neon-ninja** [comment]
I tried your code and it worked fine for me, `is_logged_in()` returned True in both cases. Maybe there's something wrong with your cookies or account? Did you get any warnings or exceptions?

**Comment by Eevaariste** [comment]
my cookies.json has all the different cookies. In my case i dont have any warnings but when i print(scraper.is_logged_in()) is false

**Comment by neon-ninja** [comment]
@Eevaariste How did you login prior to running `scraper.is_logged_in()`?

**Comment by xecgr** [comment]
Hi there, I'm reproducing this issue with the latest version of this repo
```
$ pip uninstall facebook-scraper
Found existing installation: facebook-scraper 0.2.37
Uninstalling facebook-scraper-0.2.37:
  Would remove:
    /opt/anaconda3/envs/venv/bin/facebook-scraper
    /opt/anaconda3/envs/venv/lib/python3.7/site-packages/facebook_scraper-0.2.37.dist-info/*
    /opt/anaconda3/envs/venv/lib/python3.7/site-packages/facebook_scraper/*
Proceed (y/n)? y
  Successfully uninstalled facebook-scraper-0.2.37
$ pip install facebook-scraper
Collecting facebook-scraper
  Using cached facebook_scraper-0.2.37-py3-none-any.whl (126 kB)
...
...
...
Installing collected packages: facebook-scraper
Successfully installed facebook-scraper-0.2.37
$ python
Python 3.7.7 (default, May  6 2020, 04:59:01)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from facebook_scraper import FacebookScraper
>>>
>>> scraper = FacebookScraper()
>>> scraper.login(email='supervalid', password='crendentials')
/opt/anaconda3/envs/reinout/lib/python3.7/site-packages/facebook_scraper/facebook_scraper.py:284: UserWarning: login unsuccessful
  warnings.warn('login unsuccessful')
>>> scraper.is_logged_in() == True # Should be true but is False
False
```

**Comment by neon-ninja** [comment]
Hi, please try give the latest master branch a try, I've modified the login flow a bit to support 2FA

**Comment by xecgr** [comment]
```
$ pip uninstall facebook-scraper
Found existing installation: facebook-scraper 0.2.37
Uninstalling facebook-scraper-0.2.37:
  Would remove:
    /opt/anaconda3/envs/reinout/bin/facebook-scraper
    /opt/anaconda3/envs/reinout/lib/python3.7/site-packages/facebook_scraper-0.2.37.dist-info/*
    /opt/anaconda3/envs/reinout/lib/python3.7/site-packages/facebook_scraper/*
Proceed (y/n)? y
  Successfully uninstalled facebook-scraper-0.2.37
$ pip install git+https://github.com/kevinzg/facebook-scraper.git@master
Collecting git+https://github.com/kevinzg/facebook-scraper.git@master
  Cloning https://github.com/kevinzg/facebook-scraper.git (to revision master) to /private/var/folders/d6/vp5xnc216n35bsfkjmv4f7lr0000gn/T/pip-req-build-l08h4gw4
...
...
Successfully built facebook-scraper
Installing collected packages: facebook-scraper
Successfully installed facebook-scraper-0.2.37
$ python
Python 3.7.7 (default, May  6 2020, 04:59:01)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from facebook_scraper import FacebookScraper
>>> scraper = FacebookScraper()
>>> scraper.login(email='supervalid', password='crendentials')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/reinout/lib/python3.7/site-packages/facebook_scraper/facebook_scraper.py", line 300, in login
    raise exceptions.LoginError("Login unsuccessful")
facebook_scraper.exceptions.LoginError: Login unsuccessful
>>> scraper.is_logged_in() == True # Should be true but is False
False
>>>
```
Error flow has changed a little bit but it's already there.
I've dumped `response.text` in `facebook_scraper.py:login` just after ```response = self.submit_form(response, {"email": email, "pass": password})```and I've attached to the issue
![Screen Shot 2021-05-23 at 06 33 14](https://user-images.githubusercontent.com/2619966/119248431-5b384b00-bb91-11eb-90f6-a30b0423fa17.png)
[response.html.txt](https://github.com/kevinzg/facebook-scraper/files/6527535/response.html.txt)

**Comment by neon-ninja** [comment]
This is difficult to debug, as the same code works fine with my account. If login doesn't work for you, why not pass cookies?

**Comment by xecgr** [comment]
With cookies is working again! Thanks @neon-ninja  👏
