### ISSUE TITLE
get_posts_by_url() NoneType error

### ISSUE THREAD

**Issue by nershman** [kevinzg/facebook-scraper#263]
```
list(facebook_scraper.get_posts(post_urls = ['AhSengDurian/posts/1576229315761364']))
```

error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/facebook_scraper/facebook_scraper.py", line 76, in get_posts_by_url
    elem = utils.make_html_element(elem.html.replace("</footer>", comments_area.html + "</footer>"))
AttributeError: 'NoneType' object has no attribute 'html'
```

**Comment by neon-ninja** [comment]
The scraper expects post to match this selector - `article[data-ft],div.async_like[data-ft]` - which this post does not. It's HTML differs - I think this is an uploaded photo with text, and not an actual post.

**Comment by nershman** [comment]
Also note my version is outdated. In my case the loop breaks but in the updated version that shouldn't be the case since a `continue` was added to the check if elem is None.

**Comment by neon-ninja** [comment]
I've added a new extractor class for this kind of post, called PhotoPostExtractor. With this commit (https://github.com/kevinzg/facebook-scraper/commit/ffa01a795e31b32f647635c95be6cd0afbfa4b78), I get:

```python
[{'available': True,
  'comments': 8,
  'comments_full': None,
  'factcheck': None,
  'image': 'https://scontent.fakl1-3.fna.fbcdn.net/v/t1.18169-9/fr/cp0/e15/q65/21369354_1576229315761364_2659228115994551210_n.jpg?_nc_cat=107&ccb=1-3&_nc_sid=2d5d41&_nc_ohc=6nQ7dB3ATbgAX-frg03&_nc_ht=scontent.fakl1-3.fna&tp=14&oh=a4dcee276c8a4a63b2e12c1d9a796369&oe=60C7AA3E',
  'image_lowquality': 'https://scontent.fakl1-3.fna.fbcdn.net/v/t1.18169-0/cp0/e15/q65/s320x320/21369354_1576229315761364_2659228115994551210_n.jpg?_nc_cat=107&ccb=1-3&_nc_sid=2d5d41&_nc_ohc=6nQ7dB3ATbgAX-frg03&_nc_ht=scontent.fakl1-3.fna&tp=9&oh=9f51f977a6a9cd4b40f6498af25e2fa7&oe=60C6CCDF',
  'images': ['https://scontent.fakl1-3.fna.fbcdn.net/v/t1.18169-9/fr/cp0/e15/q65/21369354_1576229315761364_2659228115994551210_n.jpg?_nc_cat=107&ccb=1-3&_nc_sid=2d5d41&_nc_ohc=6nQ7dB3ATbgAX-frg03&_nc_ht=scontent.fakl1-3.fna&tp=14&oh=a4dcee276c8a4a63b2e12c1d9a796369&oe=60C7AA3E'],
  'images_description': None,
  'images_lowquality': ['https://scontent.fakl1-3.fna.fbcdn.net/v/t1.18169-0/cp0/e15/q65/s320x320/21369354_1576229315761364_2659228115994551210_n.jpg?_nc_cat=107&ccb=1-3&_nc_sid=2d5d41&_nc_ohc=6nQ7dB3ATbgAX-frg03&_nc_ht=scontent.fakl1-3.fna&tp=9&oh=9f51f977a6a9cd4b40f6498af25e2fa7&oe=60C6CCDF'],
  'images_lowquality_description': ['No photo description available.'],
  'is_live': False,
  'likes': 74,
  'link': None,
  'original_request_url': 'AhSengDurian/posts/1576229315761364',
  'post_id': '1576229315761364',
  'post_text': 'Ah Seng Durian\n'
               '\n'
               'Durian Jackpot 🎰\n'
               '\n'
               'The birth of a durian is as the birth of a child. It takes '
               'time to grow and nurture, albeit that survivability and '
               'quality of the durians are dependent on the weather '
               'conditions.\n'
               '\n'
               'We are unique in our own individual ways, so does the durian. '
               'Every durian is different even though they may come from the '
               'same family (eg, MSW).\n'
               '\n'
               'Taste. Similar to our diverse personality and character, the '
               'durian has varying taste intensity as well. While one is able '
               'to choose a sweet or bitter durian by hitting and hearing the '
               'sound from the durian, the level of sweetness or bitterness is '
               "sometimes beyond one's control. And even so, one man's meat is "
               "another man's poison.\n"
               '\n'
               'Arils/Pods. The number of arils/pods in each fruit is '
               'naturally developed or perhaps controlled based on its '
               'physique. We are unable to determine how many arils/pods there '
               'are in each fruit.\n'
               '\n'
               'Seeds. All of us would definitely prefer to have small seeds '
               'with more flesh. However, we have recognise that the size of '
               'the seeds ranges from small to large. Not withstanding, '
               'certain cultivars such as Black Pearl, Ganghai, Golden Phoenix '
               'have seeds generally on the small size, while D24 has seeds on '
               'the larger size. We are unable to control the size of the '
               'seeds.\n'
               '\n'
               'While we always say that the durians are "包吃”, it means that '
               'we will ensure that the durians are ripe for consumption. The '
               'taste for individuals is subjective and we would recommend to '
               'do a taste test prior to accepting the durians. As for the '
               'number of arils/pods and size of the seeds which are beyond '
               'our control, we would try to top up some durians as part of '
               'our value-added services.\n'
               '\n'
               'Opening the durians is like unwrapping a present. You never '
               'know what is inside till you open it. And sometimes, with '
               'affinity and luck, you might be able to strike the durian '
               'jackpot of your expectation!\n'
               '\n'
               'We have to recognise that the durians are not factory-made and '
               "meant to be identical. It's difficult to have a durian which "
               'fulfils all the expectations one has. There are bound to have '
               "hits and misses along the way. Let's be accepting to the "
               'differences that each durian brings! 😊\n'
               '\n'
               '#ahsengdurian #unique #jackpot #duriansforthoug\n'
               'hts',
  'post_url': 'https://m.facebook.com/AhSengDurian/posts/1576229315761364',
  'reactors': None,
  'shared_post_id': None,
  'shared_post_url': None,
  'shared_text': None,
  'shared_time': None,
  'shared_user_id': None,
  'shared_username': None,
  'shares': 7,
  'text': 'Ah Seng Durian\n'
          '\n'
          'Durian Jackpot 🎰\n'
          '\n'
          'The birth of a durian is as the birth of a child. It takes time to '
          'grow and nurture, albeit that survivability and quality of the '
          'durians are dependent on the weather conditions.\n'
          '\n'
          'We are unique in our own individual ways, so does the durian. Every '
          'durian is different even though they may come from the same family '
          '(eg, MSW).\n'
          '\n'
          'Taste. Similar to our diverse personality and character, the durian '
          'has varying taste intensity as well. While one is able to choose a '
          'sweet or bitter durian by hitting and hearing the sound from the '
          'durian, the level of sweetness or bitterness is sometimes beyond '
          "one's control. And even so, one man's meat is another man's "
          'poison.\n'
          '\n'
          'Arils/Pods. The number of arils/pods in each fruit is naturally '
          'developed or perhaps controlled based on its physique. We are '
          'unable to determine how many arils/pods there are in each fruit.\n'
          '\n'
          'Seeds. All of us would definitely prefer to have small seeds with '
          'more flesh. However, we have recognise that the size of the seeds '
          'ranges from small to large. Not withstanding, certain cultivars '
          'such as Black Pearl, Ganghai, Golden Phoenix have seeds generally '
          'on the small size, while D24 has seeds on the larger size. We are '
          'unable to control the size of the seeds.\n'
          '\n'
          'While we always say that the durians are "包吃”, it means that we '
          'will ensure that the durians are ripe for consumption. The taste '
          'for individuals is subjective and we would recommend to do a taste '
          'test prior to accepting the durians. As for the number of '
          'arils/pods and size of the seeds which are beyond our control, we '
          'would try to top up some durians as part of our value-added '
          'services.\n'
          '\n'
          'Opening the durians is like unwrapping a present. You never know '
          'what is inside till you open it. And sometimes, with affinity and '
          'luck, you might be able to strike the durian jackpot of your '
          'expectation!\n'
          '\n'
          'We have to recognise that the durians are not factory-made and '
          "meant to be identical. It's difficult to have a durian which "
          'fulfils all the expectations one has. There are bound to have hits '
          "and misses along the way. Let's be accepting to the differences "
          'that each durian brings! 😊\n'
          '\n'
          '#ahsengdurian #unique #jackpot #duriansforthoug\n'
          'hts',
  'time': datetime.datetime(2017, 9, 6, 0, 0),
  'user_id': '192832840767692',
  'user_url': 'https://facebook.com/AhSengDurian/?__tn__=%2Cg',
  'username': 'Ah Seng Durian',
  'video': None,
  'video_duration_seconds': None,
  'video_height': None,
  'video_id': None,
  'video_quality': None,
  'video_size_MB': None,
  'video_thumbnail': None,
  'video_watches': None,
  'video_width': None,
  'w3_fb_url': None}]
```

**Comment by neon-ninja** [comment]
Note that comments and reactors don't seem to work with PhotoPostExtractor yet
