### ISSUE TITLE
ValueError when trying to write CSV with a video post

### ISSUE THREAD

**Issue by rezemika** [kevinzg/facebook-scraper#302]
Hi!
I just tried to scrape a Facebook page (from command line) and saving it to a CSV file, and after some time, I get a ValueError.
Here is the end of the logs I get with verbose mode.
I have Python 3.9 and facebook-scraper 0.2.38.

```
[3084570254941333] Extract method extract_link didn't return anything
[3084570254941333] Extract method extract_video didn't return anything
[3084570254941333] Extract method extract_video_thumbnail didn't return anything
[3084570254941333] Extract method extract_video_id didn't return anything
[3084570254941333] Extract method extract_video_meta didn't return anything
[3084570254941333] Extract method extract_factcheck didn't return anything
data-ft attribute not found
Traceback (most recent call last):
  File "<envpath>/venv/bin/facebook-scraper", line 8, in <module>
    sys.exit(run())
  File "<envpath>/venv/lib/python3.9/site-packages/facebook_scraper/__main__.py", line 48, in run
    write_posts_to_csv(
  File "<envpath>/venv/lib/python3.9/site-packages/facebook_scraper/__init__.py", line 205, in write_posts_to_csv
    dict_writer.writerows(list_of_posts)
  File "/usr/lib/python3.9/csv.py", line 157, in writerows
    return self.writer.writerows(map(self._dict_to_list, rowdicts))
  File "/usr/lib/python3.9/csv.py", line 149, in _dict_to_list
    raise ValueError("dict contains fields not in fieldnames: "
ValueError: dict contains fields not in fieldnames: 'video_ids', 'videos'
```

Here is the command I tried: `facebook-scraper --filename smp.csv --verbose streetmedicparis` (for [this page](https://facebook.com/streetmedicparis/)).

I did not find an issue about it, I hope this is not a repost.
I'm sorry, I don't have the time to look for where it comes from by myself right now, but it's probably related to [this line](https://github.com/kevinzg/facebook-scraper/blob/d28a4dbffb2ba452d1c1f716283bcdad1549affd/facebook_scraper/__init__.py#L253), or to the way dicts of posts are created...

**Comment by rezemika** [comment]
When testing with another page (`streetmedicnantes` and with `--reactions`), I also get: `ValueError: dict contains fields not in fieldnames: 'fetched_time'`.

**Comment by neon-ninja** [comment]
This commit should fix this problem - https://github.com/kevinzg/facebook-scraper/commit/9820657f5fb99c64721e9cf604c6b5defb56dd40

**Comment by rezemika** [comment]
Thank you for your really fast answer, and fix! :)
