### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPSConnectionPool

### ISSUE THREAD

**Issue by LightMoon** [kevinzg/facebook-scraper#408]
Hi,

I am getting the following exception. I can browse m.facebook.com via browser apparently sessions initiated by requests can not reach out. Any thoughts?

`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='m.facebook.com', port=443): Read timed out.`

```python

Python 3.8.2 (default, Apr  8 2021, 23:19:18) 
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
runfile('/Users/sam/PycharmProjects/FBScraper-Prod/venv/Profile_info.py', wdir='/Users/sam/PycharmProjects/FBScraper-Prod/venv')
/Users/sam/PycharmProjects/FBScraper-Prod/venv/lib/python3.8/site-packages/facebook_scraper/facebook_scraper.py:413: UserWarning: Locale detected as en_GB - for best results, set to en_US
  warnings.warn(f"Locale detected as {locale} - for best results, set to en_US")
Traceback (most recent call last):
  File "/Users/sam/PycharmProjects/FBScraper-Prod/venv/lib/python3.8/site-packages/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/Users/sam/PycharmProjects/FBScraper-Prod/venv/lib/python3.8/site-packages/urllib3/response.py", line 764, in read_chunked
    self._update_chunk_length()
  File "/Users/sam/PycharmProjects/FBScraper-Prod/venv/lib/python3.8/site-packages/urllib3/response.py", line 694, in _update_chunk_length
    line = self._fp.fp.readline()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/sam/PycharmProjects/FBScraper-Prod/venv/lib/python3.8/site-packages/requests/models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/Users/sam/PycharmProjects/FBScraper-Prod/venv/lib/python3.8/site-packages/urllib3/response.py", line 572, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/Users/sam/PycharmProjects/FBScraper-Prod/venv/lib/python3.8/site-packages/urllib3/response.py", line 793, in read_chunked
    self._original_response.close()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/sam/PycharmProjects/FBScraper-Prod/venv/lib/python3.8/site-packages/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='m.facebook.com', port=443): Read timed out.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/sam/PycharmProjects/FBScraper-Prod/venv/Profile_info.py", line 7, in <module>
    profile = get_profile(userId, cookies="cookies.json")
  File "/Users/sam/PycharmProjects/FBScraper-Prod/venv/lib/python3.8/site-packages/facebook_scraper/__init__.py", line 69, in get_profile
    return _scraper.get_profile(account, **kwargs)
  File "/Users/sam/PycharmProjects/FBScraper-Prod/venv/lib/python3.8/site-packages/facebook_scraper/facebook_scraper.py", line 186, in get_profile
    response = self.get(account)
  File "/Users/sam/PycharmProjects/FBScraper-Prod/venv/lib/python3.8/site-packages/facebook_scraper/facebook_scraper.py", line 420, in get
    response = self.session.get(url=url, **self.requests_kwargs, **kwargs)
  File "/Users/sam/PycharmProjects/FBScraper-Prod/venv/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/Users/sam/PycharmProjects/FBScraper-Prod/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/sam/PycharmProjects/FBScraper-Prod/venv/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
    r.content
  File "/Users/sam/PycharmProjects/FBScraper-Prod/venv/lib/python3.8/site-packages/requests/models.py", line 831, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/Users/sam/PycharmProjects/FBScraper-Prod/venv/lib/python3.8/site-packages/requests/models.py", line 760, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='m.facebook.com', port=443): Read timed out.

```

**Comment by neon-ninja** [comment]
Try increase the default timeout with the timeout parameter

**Comment by neon-ninja** [comment]
I've increased the default timeout in https://github.com/kevinzg/facebook-scraper/commit/0d1848876d8b5fb407e729933c03987896051101
