### ISSUE TITLE
Scraping pages limit

### ISSUE THREAD

**Issue by Whisby25** [kevinzg/facebook-scraper#414]
Hey there! I am using facebook-scraper for my thesis reaserch. Its really great tool. I just have one issue. I think it is caused by exceeding the number of pages existing on a specific profile. 
For example if I determine the numer of pages to be 50 - scraper works properly. If I change the number to higher, at some point I get below error log. 
Is there a way to bypass this? Or can I get the information on number of pages for the profiles Im trying to scrap? Thanks in advance for all the tips!

Traceback (most recent call last):
  File "/home/michal/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/michal/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/michal/env/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/michal/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/michal/env/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/michal/env/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/michal/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/michal/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/michal/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='m.facebook.com', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "facebook.py", line 13, in <module>
    for post in get_posts(user, pages=500, cookies='/home/michal/env/cookie.json'):
  File "/home/michal/env/lib/python3.8/site-packages/facebook_scraper/facebook_scraper.py", line 555, in _generic_get_posts
    for i, page in zip(counter, iter_pages_fn()):
  File "/home/michal/env/lib/python3.8/site-packages/facebook_scraper/page_iterators.py", line 63, in generic_iter_pages
    response = request_fn(next_url)
  File "/home/michal/env/lib/python3.8/site-packages/facebook_scraper/facebook_scraper.py", line 429, in get
    response = self.session.get(url=url, **self.requests_kwargs, **kwargs)
  File "/home/michal/env/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/michal/env/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/michal/env/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/michal/env/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='m.facebook.com', port=443): Read timed out. (read timeout=5)

**Comment by neon-ninja** [comment]
Try increase the timeout with the timeout parameter

**Comment by Whisby25** [comment]
```
from facebook_scraper import get_posts
import pandas as pd

users = ['nintendo', 'zuck']

for user in users:
    filename = user + '.csv'

    df_ori = pd.DataFrame(columns = ['username', 'time', 'likes', 'comments', 'shares', 'reactions', 'post_text'])

    for post in get_posts(user, pages=500, timeout = 60, cookies='/home/whisby25/env/cookie.json', extra_info=True):
        dataframe = post
        df = pd.DataFrame.from_dict(dataframe, orient='index')
        df = df.transpose()
        print("writing post to file")
        df_ori = df_ori.append(df)

    print("saving file")
    df_ori.to_csv(filename, index = False)


```
Solution you provided helped me! Thank you so much! I dont get the timeout error anymore. 

The problem is that I still get some empty csv files for provided users when I am using the above code. For some users I get all of the posts, while for others I am getting empty files or just few posts that they have shared. 

I expect that the issue might be trivial but trust me I have tried everything for over 2 days :( 

Do you have any tips for me?

**Comment by neon-ninja** [comment]
Try enable debug logging as per the issue template
