### ISSUE TITLE
get_profile - IndexError: list index out of range

### ISSUE THREAD

**Issue by milesgratz** [kevinzg/facebook-scraper#450]
Hey there - I'm getting this error for a particular user! Will attempt to fix it myself and comment on here with the fix, if possible. 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/fbscraping/venv-original/lib/python3.8/site-packages/facebook_scraper/__init__.py", line 69, in get_profile
    return _scraper.get_profile(account, **kwargs)
  File "/opt/fbscraping/venv-original/lib/python3.8/site-packages/facebook_scraper/facebook_scraper.py", line 199, in get_profile
    profile_photo = photo_links[1]
IndexError: list index out of range
```

![image](https://user-images.githubusercontent.com/17114534/130364010-9375a9ec-2dd2-40cc-bdd2-f9c77cbe0c26.png)

**Comment by neon-ninja** [comment]
I already fixed this in https://github.com/kevinzg/facebook-scraper/commit/fe6d504cfce0d5bc782537b2819b4379e3e53bb1 - try update to latest master
