### ISSUE TITLE
flask wsgi modulenotfound error

### ISSUE THREAD

**Issue by okandas** [kevinzg/facebook-scraper#528]
First of all top module .. 

I seem to be unable to access facebook-scrapper using apache and flask .. This work if I use the flask development server
```
[Thu Oct 21 21:10:53.714241 2021] [wsgi:error] [pid 4289] [client ::1:65271] mod_wsgi (pid=4289): Failed to exec Python script file '/var/app/scrapper/scrapper.wsgi'.
[Thu Oct 21 21:10:53.714380 2021] [wsgi:error] [pid 4289] [client ::1:65271] mod_wsgi (pid=4289): Exception occurred processing WSGI script '/var/app/scrapper/scrapper.wsgi'.
[Thu Oct 21 21:10:53.715675 2021] [wsgi:error] [pid 4289] [client ::1:65271] Traceback (most recent call last):
[Thu Oct 21 21:10:53.715777 2021] [wsgi:error] [pid 4289] [client ::1:65271]   File "/var/app/scrapper/scrapper.wsgi", line 10, in <module>
[Thu Oct 21 21:10:53.715804 2021] [wsgi:error] [pid 4289] [client ::1:65271]     from scrapper import app as application
[Thu Oct 21 21:10:53.715826 2021] [wsgi:error] [pid 4289] [client ::1:65271]   File "/var/app/scrapper/scrapper.py", line 2, in <module>
[Thu Oct 21 21:10:53.715841 2021] [wsgi:error] [pid 4289] [client ::1:65271]     from facebook_scraper import get_posts
[Thu Oct 21 21:10:53.715891 2021] [wsgi:error] [pid 4289] [client ::1:65271] ModuleNotFoundError: No module named 'facebook_scraper'
```

```
Requirement already satisfied: facebook-scraper in /home/okandas/work/scrapper/scrape/lib/python3.8/site-packages (0.2.48)

(scrape) ls scrape/lib/python3.8/site-packages/
Flask-2.0.2.dist-info       __pycache__      click-8.0.3.dist-info  itsdangerous-2.0.1.dist-info  pip-20.0.2.dist-info           pkg_resources-0.0.0.virtualenv  werkzeug
Jinja2-3.0.2.dist-info      _virtualenv.pth  easy_install.py        jinja2                        pip-20.0.2.virtualenv          setuptools                      wheel
MarkupSafe-2.0.1.dist-info  _virtualenv.py   flask                  markupsafe                    pkg_resources                  setuptools-44.0.0.dist-info     wheel-0.34.2.dist-info
Werkzeug-2.0.2.dist-info    click            itsdangerous           pip                           pkg_resources-0.0.0.dist-info  setuptools-44.0.0.virtualenv    wheel-0.34.2.virtualenv

```

**Comment by neon-ninja** [comment]
Or just don't use venvs, and install packages system-wide
