### ISSUE TITLE
NameError

### ISSUE THREAD

**Issue by Sophiead** [kevinzg/facebook-scraper#568]
I receive the error "NameError: name 'unichr' is not defined". 
How can I solve this issue? 
Thank you in advance

**Comment by neon-ninja** [comment]
What code causes this error? Can you post the full stack trace

**Comment by Sophiead** [comment]
I've used the command: facebook-scraper --encoding utf-8 --filename nameoftheFBpage.csv --pages 20000 nameoftheFBpage

**Comment by neon-ninja** [comment]
You need to update lxml. Try `pip install -U lxml`

**Comment by Sophiead** [comment]
Now I receive for each page I tried to scrape the message "couldn't get any posts". Can I solve this issue? Many thanks

**Comment by neon-ninja** [comment]
What page are you having this problem with? Try pass cookies as per the readme

**Comment by Sophiead** [comment]
I tried it for the page: https://www.facebook.com/ADVNvzw
I passed cookies but I received the following error:
Traceback (most recent call last):
  File "/Users/XX/Documents/profile_FB.py", line 2, in <module>
    get_group_info("ADVNvzw") # or get_group_info("ADVNvzw", cookies="cookies.json")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/facebook_scraper/__init__.py", line 120, in get_group_info
    return _scraper.get_group_info(group, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/facebook_scraper/facebook_scraper.py", line 501, in get_group_info
    resp = self.get(url).html
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/facebook_scraper/facebook_scraper.py", line 622, in get
    raise exceptions.UnexpectedResponse("Your request couldn't be processed")
facebook_scraper.exceptions.UnexpectedResponse: Your request couldn't be processed

**Comment by neon-ninja** [comment]
You need to update to the latest version of facebook-scraper

**Comment by Sophiead** [comment]
With which command can I do that? Thank you in advance

**Comment by neon-ninja** [comment]
`pip install -U facebook-scraper`

**Comment by Sophiead** [comment]
It works! Thank you very much. The only problem I still have the tool doesn't work on MacOS Catalina. I can properly install it, but when I use the commands I get the message: "zsh: command not found: facebook-scraper". Has the tool been tested on this version?

**Comment by neon-ninja** [comment]
I don't have a Mac, so no. Try `python -m facebook_scraper -h` and see if that works for you
