### ISSUE TITLE
Query all posts?

### ISSUE THREAD

**Issue by dereck255** [kevinzg/facebook-scraper#59]
Is there a way to query for a keyword across all posts? Or do I have to pick a specific user page?

**Comment by neon-ninja** [comment]
Like search? This is possible in theory, the scraper could make a web request to https://m.facebook.com/search/posts/?q=search%20query

**Comment by suarezjessie** [comment]
Hi @neon-ninja, I've been attempting to use the library to get search results. I've tried using the `get` function but it throws out a 404 error for this sample search URL `https://m.facebook.com/search/posts/?q=nintendo`. Below is the code and error

**Error**
```
Traceback (most recent call last):
  File "fb_scrape_sample.py", line 6, in <module>
    for post in FacebookScraper().get(url):
  File "C:\Users\jessie.suarez\Anaconda3\envs\social_listening\lib\site-packages\facebook_scraper\facebook_scraper.py", line 473, in get
    response.raise_for_status()
  File "C:\Users\jessie.suarez\Anaconda3\envs\social_listening\lib\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://m.facebook.com/search/posts/?q=nintendo
(social_listening)
```

**Code Snippet**
```
from facebook_scraper import FacebookScraper, set_cookies

set_cookies("fb_cookie.txt")

url = 'https://m.facebook.com/search/posts/?q=nintendo'
for post in FacebookScraper().get(url):
	print(post)
	break
```

Thanks!
