### ISSUE TITLE
Question regarding profile comments on posts ('comment_time')

### ISSUE THREAD

**Issue by potterthecop** [kevinzg/facebook-scraper#624]
Hello, Kevin
I noticed that in M version of Facebook, post's comment time is displayed as '6 mon' , '1y' , '1mon' and isn't interpreted correctly.
Instead, in mbasic version of Facebook, date and time is represented better.

Can you see a solution to fix this issue? I'm using v. 0251 with cookies passed and English language.

Thanks in advance :)

**Comment by neon-ninja** [comment]
Sure, there's already a function to use mbasic (`set_noscript(True)`). I think if precise comment times are a requirement for you, then using mbasic for this reason makes sense. My latest commit (https://github.com/kevinzg/facebook-scraper/commit/eb14ab9461345a13c80f572fd92f8ed6f9a57980) fixes some minor issues to get mbasic comment extraction working again. With that commit, and this test code:

```python
from facebook_scraper import *
set_noscript(True)
set_cookies("cookies.json")

post = next(get_posts(post_urls=[4876511549099926], options={"comments": "generator"}))
for comment in post["comments_full"]:
    print(comment["comment_time"])
```
I get this output:

```python
2022-01-03 16:36:00
2022-01-03 04:05:00
2022-01-03 04:02:00
2022-01-03 22:06:00
2022-01-03 04:37:00
2022-01-03 05:04:00
2022-01-03 11:35:00
2022-01-03 07:15:00
2022-01-03 10:35:00
2022-01-03 04:11:00
2022-01-03 07:24:00
2022-01-06 08:23:00
2022-01-03 04:16:00
2022-01-03 12:15:00
2022-01-03 07:25:00
2022-01-03 11:25:00
2022-01-03 05:57:00
2022-01-04 00:08:00
2022-01-03 04:49:00
2022-01-04 07:17:00
2022-01-03 04:08:00
2022-01-03 10:42:00
2022-01-05 00:00:00
2022-01-04 04:07:00
2022-01-03 17:59:00
2022-01-03 08:05:00
2022-01-04 00:00:00
2022-01-03 13:52:00
2022-01-04 00:00:00
2022-01-04 05:24:00
2022-01-03 04:11:00
2022-01-06 22:43:26
2022-01-06 07:42:00
2022-01-03 04:56:00
2022-01-03 04:44:00
2022-01-04 00:00:00
2022-01-03 05:44:00
2022-01-04 00:00:00
2022-01-04 05:52:00
2022-01-03 04:07:00
2022-01-03 04:30:00
2022-01-03 15:32:00
2022-01-03 04:23:00
2022-01-06 09:04:00
2022-01-03 08:59:00
2022-01-06 22:43:27
2022-01-03 04:31:00
2022-01-03 05:43:00
2022-01-03 10:59:00
2022-01-04 00:47:00
2022-01-04 00:00:00
2022-01-03 12:45:00
2022-01-03 05:01:00
2022-01-03 13:33:00
2022-01-03 11:29:00
2022-01-03 05:23:00
2022-01-03 10:21:00
2022-01-03 06:17:00
2022-01-06 06:37:00
2022-01-03 07:31:00
2022-01-03 04:29:00
2022-01-03 04:14:00
2022-01-05 00:00:00
2022-01-03 04:43:00
2022-01-03 04:37:00
2022-01-04 00:00:00
```

**Comment by potterthecop** [comment]
Thanks, @kevinzg !

Your example, regarding this particular post work on my laptop also.

But when i try to get all posts and all comments from a Facebook user, the code returns nothing.

Then i used enable_logging(logging.DEBUG) and i got:

Exception while requesting URL: https://m.facebook.com/USER ID/posts/
Exception: HTTPError('404 Client Error: Not Found for url: https://m.facebook.com/USER ID/posts/?locale=en_US')


I use this code:

`from facebook_scraper import *

set_noscript(True)

list = []
for post in get_posts('USERNAME', cookies=r'C:\Users\...path....\Cookies_IM.json', options={"comments": True, "reactors": True, "comment_reactors":  True}):
    list.append(post)
pd.DataFrame(list).to_csv(r"C:\Users\....path....\tests.csv", index=False)`

**Comment by neon-ninja** [comment]
What user are you having this problem with?

**Comment by potterthecop** [comment]
Thanks for the reply, @kevinzg 
For example, regarding this user: https://www.facebook.com/melu.iamandei
I want to extract all his posts and of course...full comments with date.

Regarding the suggestion with noscript on and off...i am somehow new to python..maybe you can write here a little example?

Thanks alot!

**Comment by neon-ninja** [comment]
Sure - something like this should work:

```python
set_cookies("cookies.json")

# Using m.facebook.com style
posts = list(get_posts("melu.iamandei", options={"allow_extra_requests": False}))
print(f"Got {len(posts)} posts, with {sum(p['comments'] for p in posts)} total comments")
# Using mbasic.facebook.com style
set_noscript(True)
posts = get_posts(post_urls=[p["post_id"] for p in posts], options={"comments": True})
for post in posts:
    print(post["post_id"])
    for comment in post["comments_full"]:
        print(comment["comment_time"])
    break
```
outputs:

```python
Got 8 posts, with 258 total comments
636296867392537
2021-10-30 00:00:00
2021-10-31 00:00:00
2021-10-31 00:00:00
2021-10-31 00:00:00
2021-11-01 00:00:00
2021-11-01 00:00:00
2021-11-03 00:00:00
2021-11-04 00:00:00
2021-11-04 00:00:00
2021-11-05 00:00:00
2021-10-28 00:00:00
2021-10-28 00:00:00
2021-10-29 00:00:00
2021-10-29 00:00:00
2021-10-29 00:00:00
2021-10-29 00:00:00
2021-10-29 00:00:00
2021-10-29 00:00:00
2021-10-29 00:00:00
2021-10-30 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-28 00:00:00
2021-10-28 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
2021-10-27 00:00:00
```

**Comment by potterthecop** [comment]
Many thanks for all that patience, @kevinzg 
One more question, please?

Do you know what could be the cause for this error?

Got 7 posts, with 258 total comments
Traceback (most recent call last):
  File "testare.py", line 13, in <module>
    for post in posts:
  File "C:\Python\Python38\lib\site-packages\facebook_scraper\facebook_scraper.py", line 143, in get_posts_by_url
    elem = utils.make_html_element(
  File "C:\Python\Python38\lib\site-packages\facebook_scraper\utils.py", line 130, in make_html_element
    pq_element = PyQuery(html)[0]  # PyQuery is a list, so we take the first element
  File "C:\Python\Python38\lib\site-packages\pyquery\pyquery.py", line 217, in __init__
    elements = fromstring(context, self.parser)
  File "C:\Python\Python38\lib\site-packages\pyquery\pyquery.py", line 57, in fromstring
    result = getattr(etree, meth)(context)
  File "src\lxml\etree.pyx", line 3252, in lxml.etree.fromstring
  File "src\lxml\parser.pxi", line 1907, in lxml.etree._parseMemoryDocument
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.


I downloaded the modified files from the last commit (4 days ago) and I overwritten it in C:\Python\Python38\Lib\site-packages\facebook_scraper.
I have to update other package or..?

Thanks and sorry to be such pain in the..:)

**Comment by neon-ninja** [comment]
Ah sorry, I saw that error too and made a fix, but forgot to commit it. Try https://github.com/kevinzg/facebook-scraper/commit/0c2c0caa131523a7c6c50492aa769f8e3e75c070

**Comment by potterthecop** [comment]
Thank you, @kevinzg !
In works now! :)

**Comment by potterthecop** [comment]
@kevinzg , one more question, when you have time.
it seems that, regarding the commenter_id, commenter_url i always get None value.
Commenter_name is extracted but it would be nice if i had one identifier :)
Thanks!

**Comment by neon-ninja** [comment]
I don't see commenter ids in the mbasic source code, but commenter_urls seem to be there - https://github.com/kevinzg/facebook-scraper/commit/b2259aac1c5f6b7dc60c2f73ce8c0da2960c3036 should surface them
