### ISSUE TITLE
set_cookies throws UnexpectedResponse

### ISSUE THREAD

**Issue by suarezjessie** [kevinzg/facebook-scraper#626]
I've used this library last year and it worked when I tried the example post extraction. However, now, it seems like my cookie doesn't work anymore. I simply followed the instruction on extracting the cookie via EditThisCookie Extension in Chrome and saved the output to a text file. I tried logging in again and refreshing the cookie, I've also deleted cookies stored but it still isn't working. I also ensured that `xs` and `c_user` was in the cookie. It was the same method that I used last year, but I am not able to successfully do it now. 

The version I'm using is `facebook-scraper==0.2.47`

Below is the stack trace

```
Traceback (most recent call last):
  File "fb_scrape_sample.py", line 12, in <module>
    set_cookies("fb_cookie.txt")
  File "C:\Users\jessie.suarez\Anaconda3\envs\social_listening\lib\site-packages\facebook_scraper\__init__.py", line 35, in set_cookies
    if not _scraper.is_logged_in():
  File "C:\Users\jessie.suarez\Anaconda3\envs\social_listening\lib\site-packages\facebook_scraper\facebook_scraper.py", line 571, in is_logged_in
    self.get('https://m.facebook.com/settings')
  File "C:\Users\jessie.suarez\Anaconda3\envs\social_listening\lib\site-packages\facebook_scraper\facebook_scraper.py", line 497, in get
    raise exceptions.UnexpectedResponse("Your request couldn't be processed")
facebook_scraper.exceptions.UnexpectedResponse: Your request couldn't be processed

```

And then here's the code that I used

```
from facebook_scraper import get_posts, enable_logging, set_cookies
import logging
import pprint
enable_logging(logging.DEBUG)

set_cookies("fb_cookie.txt")
```

**Comment by suarezjessie** [comment]
Closing issue, updated to latest version and it worked
