### ISSUE TITLE
resume from where interrupted

### ISSUE THREAD

**Issue by msaljoug** [kevinzg/facebook-scraper#637]
Hi, If the process is interrupted for any reason, is there a way to resume pulling data from where it stopped? If so, could you show it in an example?

**Comment by neon-ninja** [comment]
Yes. What process are you referring to? `get_posts`? If so, see https://github.com/kevinzg/facebook-scraper/issues/310#issuecomment-852652846

**Comment by msaljoug** [comment]
thanks for your reply. #310 starts from the beginning, though. I implemented in my code and after getting temporarily banned, it started scraping the page from the beginning.

**Comment by neon-ninja** [comment]
How far did you get before the temp ban?

**Comment by msaljoug** [comment]
584 , which was spread over 14 months.

**Comment by msaljoug** [comment]
this is the ```start_url ``` when the code was interrupted.  the ```post_id``` in this variable is that of the very first post. 
```
https://m.facebook.com/page_content_list_view/more/?page_id=19600366397&start_cursor={%22timeline_cursor%22:%22AQHRAXqFRNb-mt9YWBWEACwpBtaN3Q7S83v5NQ8UNsUSqUHsG-KkjD-S4v72UosIy4inYdSZvoJ7gPflQXuxyaTut8lBzFjgB1boY_LXgc5Rga-D1c6v7os0jPsJQKZ1227F%22,%22timeline_section_cursor%22:null,%22has_next_page%22:true}&num_to_fetch=200&surface_type=posts_tab
```
In other words, the start_url does not seem to change, and that is why the process starts from the very beginning.

**Comment by neon-ninja** [comment]
Does it work if you only scrape the posts, and not reactors/comments/HQ images? For example:

```python
import time
from facebook_scraper import *

results = []
start_url = None
def handle_pagination_url(url):
    global start_url
    start_url = url
    if results:
        print(f"{len(results)}: {results[-1]['time']}: {start_url}")
set_cookies("cookies.json")
while True:
    try:
        for post in get_posts("TwiddyOuterBanks", page_limit=None, start_url=start_url, request_url_callback=handle_pagination_url, options={
            "allow_extra_requests": False,
            "posts_per_page": 200
        }):
            results.append(post)
        print("All done")
        break
    except exceptions.TemporarilyBanned:
        print("Temporarily banned, sleeping for 10m")
        time.sleep(600)
```
outputs:

```python
1: 2022-01-20 02:59:51: https://m.facebook.com/page_content_list_view/more/?page_id=19600366397&start_cursor={"timeline_cursor":"AQHRUnFFvQgiu9yrNlYr6zRrguLGPYJ-74NsTvJPOn8frzj-lJohjFUctlnEQY0LXIWQsaUDIQaXa2Vqu1t7x-M2T6U1Ae1K1LNK69S3W0T7PNWYsYC12PwS2paatYK4mD4w","timeline_section_cursor":null,"has_next_page":true}&num_to_fetch=200&surface_type=posts_tab
201: 2021-08-02 09:43:00: https://m.facebook.com/page_content_list_view/more/?page_id=19600366397&start_cursor={"timeline_cursor":"AQHR-XVwdTFHw58DVGajbvoMdpcWyzLOPzWESPaB9kelFhc_E2DkF0dpBJ2y5xrP_afDUj7v1I70r9XEw8jQVcN4ABkP66PDXjoLKoFf-Wm6FEBcL5Tc0gZqf-rQvVIfF7BO","timeline_section_cursor":null,"has_next_page":true}&num_to_fetch=200&surface_type=posts_tab
401: 2021-02-04 05:20:15: https://m.facebook.com/page_content_list_view/more/?page_id=19600366397&start_cursor={"timeline_cursor":"AQHRrMM68wwESxVhfI93lp1AnQDwd7c1HzrieE2DgQqN0_p8jNOoJXdEcpyqDIF8GAE2Ni3NKLSe62rEXFHIjyNws54TCCOEN6-h1v1d31x4IOatW5170savSiv1veTSPiXa","timeline_section_cursor":null,"has_next_page":true}&num_to_fetch=200&surface_type=posts_tab
601: 2020-10-07 10:26:07: https://m.facebook.com/page_content_list_view/more/?page_id=19600366397&start_cursor={"timeline_cursor":"AQHRLXEgDDBRJ7QtRH4hvdbBFytMf8rTk9GrYdQ3ujn3rieYeRiWXm-sIJo4CfJfSxHbV_T9lNYze5hkm4GvlG5vp-05xrGZSu3h01-9w-gpFOWOERmm5DyRP2y_VEPc8EIL","timeline_section_cursor":null,"has_next_page":true}&num_to_fetch=200&surface_type=posts_tab
801: 2020-07-12 13:30:00: https://m.facebook.com/page_content_list_view/more/?page_id=19600366397&start_cursor={"timeline_cursor":"AQHR6jyZS_PewCiPC-TErRCb9E3GRntYQNQF62hLe19JKxdHggZRNByanvx38s8cwpD--2y644oy7-o2XraURU-rxkQ1eaSeoBlTCCWM9yBp_JnfChSCc6NduZXx0z-Y9Ti6","timeline_section_cursor":null,"has_next_page":true}&num_to_fetch=200&surface_type=posts_tab
1001: 2020-05-29 00:30:54: https://m.facebook.com/page_content_list_view/more/?page_id=19600366397&start_cursor={"timeline_cursor":"AQHRNp_Y_B8Bo_-wJFqh7X0bgcic_-CPCSHOXBWbt_cruCGbq-aYnY0wX-JBWA8iN351ecIjscoGuSZNi3MeUxCq9xIjUm6cT7Xz3zdYW0DI_UqixkGw5FkBIRNOyCVQnqM7","timeline_section_cursor":null,"has_next_page":true}&num_to_fetch=200&surface_type=posts_tab
1201: 2020-03-22 05:31:12: https://m.facebook.com/page_content_list_view/more/?page_id=19600366397&start_cursor={"timeline_cursor":"AQHRe5WFdk8ehkLLb9i9TD33TULzTF_jcDsvD0z6yCK_vM_LBday11DEMuFzcDZvf47GmPViG5PnY7vGWW1q6aF7CR6gxW89aXkdZwIYqzpKDvP3ECrk_vkFe4vbrBK-J6yG","timeline_section_cursor":null,"has_next_page":true}&num_to_fetch=200&surface_type=posts_tab
1401: 2020-01-26 05:38:46: https://m.facebook.com/page_content_list_view/more/?page_id=19600366397&start_cursor={"timeline_cursor":"AQHRMxlMPGbVI00MYOvuGmTohBYlu1oCQaCcu9XLgb9H844U22xDUHhZDKHxtu9Z9vj70knJMu_WabgITvZVzz6vCVZORarUHs3gcMoXaYmZQ8hedQM7P2j3b3cuXeBbPFwD","timeline_section_cursor":null,"has_next_page":true}&num_to_fetch=200&surface_type=posts_tab
1601: 2019-11-23 18:00:00: https://m.facebook.com/page_content_list_view/more/?page_id=19600366397&start_cursor={"timeline_cursor":"AQHR_G1fh3kMILbE9jPS1mrb_TvgW3_sQmKjupmasYbhxVSCziAEPN3pjfxyrvv2hk3xMaH7xhFYcJYlSUeywUaL4QsQHkqXEG5p_iw2_4onikGGilyi1V-hWGudCNO8GI2a","timeline_section_cursor":null,"has_next_page":true}&num_to_fetch=200&surface_type=posts_tab
1801: 2019-09-16 12:16:00: https://m.facebook.com/page_content_list_view/more/?page_id=19600366397&start_cursor={"timeline_cursor":"AQHRQ7OptCUXNJ_288pdlVVjS2aoYLt3VHaCKnEla7Gleg1ggzUYeQhHe_uTaAWV3fhjx2snZF_pZlksO_IkxcV6XFYwsX0gPnbIf9Jow6f8jhSuFq1QZ2_JxunWLnIbhNNY","timeline_section_cursor":null,"has_next_page":true}&num_to_fetch=200&surface_type=posts_tab
```

which seem to valid and re-usable start_urls

**Comment by msaljoug** [comment]
Unfortunately, at the very least I need the comments for my research. The code you provided seems to work well if one doesn't need the comments, but is there a way to fix this issue when pulling the comments, as well?

**Comment by neon-ninja** [comment]
At this sort of scale, I think it might make sense to decouple these processes. Because, the number of comments very quickly get into the thousands, even with just a few hundred posts. And comments only come in pages of 30, so the number of requests required to get all comments very quickly adds up. So, I would recommend scraping posts first, storing the results, and then retrieving the comments afterwards (which you can do using the `post_urls` argument to `get_posts`).

**Comment by msaljoug** [comment]
This intuitively makes sense. So, I should basically feed the ```post_url``` field to the code and ask it to collect comments for each url?

Would you mind also showing it in an example?

**Comment by msaljoug** [comment]
> ```python
> 19600366397
> ```

Also, all ```page_id```'s in your output are the same. This is what happens when I try to pull comments, too. I do not know if this creates the problem or not, though.

**Comment by neon-ninja** [comment]
Sure:

```python
post = next(get_posts(post_urls=["10158228969136398"], options={
    "comments": True,
    "reactors": True,
}))
pprint(post)
```
outputs:
```python
{'available': True,
 'comments': 3,
 'comments_full': [{'comment_id': '10158229485061398',
                    'comment_image': None,
                    'comment_reaction_count': 28,
                    'comment_reactions': {'like': 25, 'love': 3},
                    'comment_reactors': [{'link': 'https://facebook.com/TwiddyOuterBanks/?fref=pb',
                                          'name': 'Twiddy & Co',
                                          'type': 'like'}],
                    'comment_text': 'Will any of the breweries be open in '
                                    'November? Or most everything be shut '
                                    'down?',
                    'comment_time': datetime.datetime(2021, 7, 20, 12, 38, 1),
                    'comment_url': 'https://facebook.com/10158229485061398',
                    'commenter_id': '100000417017431',
                    'commenter_meta': None,
                    'commenter_name': 'Chris Wuertz',
                    'commenter_url': 'https://facebook.com/chris.wuertz.71?fref=nf&rc=p&refid=52&__tn__=R',
                    'replies': [{'comment_id': '10158229940411398',
                                 'comment_image': None,
                                 'comment_reaction_count': None,
                                 'comment_reactions': None,
                                 'comment_reactors': [],
                                 'comment_text': "Hey Chris! We're not aware "
                                                 'of offseason hours for the '
                                                 'places listed quite yet for '
                                                 '2022. Usually, The Brewing '
                                                 'Station, The Jug Shop, Jack '
                                                 'Browns, and the Lost Colony '
                                                 'Brewing are open to our '
                                                 'knowledge. Most of these '
                                                 'restaurants/\n'
                                                 'breweries have social media '
                                                 "pages that they'll like post "
                                                 'their off-season hours on if '
                                                 'you want to follow along '
                                                 'there!',
                                 'comment_time': datetime.datetime(2021, 7, 20, 12, 38, 1),
                                 'comment_url': 'https://facebook.com/10158229940411398',
                                 'commenter_id': '19600366397',
                                 'commenter_meta': 'Author',
                                 'commenter_name': 'Twiddy & Co',
                                 'commenter_url': 'https://facebook.com/TwiddyOuterBanks/?rc=p&refid=52&__tn__=%7ERR'}]},
                   {'comment_id': '10158230751261398',
                    'comment_image': None,
                    'comment_reaction_count': 28,
                    'comment_reactions': {'like': 25, 'love': 3},
                    'comment_reactors': [{'link': 'https://facebook.com/joe.rokita?fref=pb',
                                          'name': 'Joe Rokita',
                                          'type': 'like'}],
                    'comment_text': 'Brian Finkelstein\nJoe Rokita',
                    'comment_time': datetime.datetime(2021, 7, 20, 12, 38, 1),
                    'comment_url': 'https://facebook.com/10158230751261398',
                    'commenter_id': '633984460',
                    'commenter_meta': None,
                    'commenter_name': 'Kristy Finkelstein',
                    'commenter_url': 'https://facebook.com/kfinkelstein?fref=nf&rc=p&refid=52&__tn__=R',
                    'replies': []}],
 'factcheck': None,
 'fetched_time': datetime.datetime(2022, 1, 20, 12, 38, 1, 287867),
 'image': 'https://www.twiddy.com/blog/wp-content/uploads/2019/08/NOBBC_flight2.jpg',
 'image_id': None,
 'image_ids': [],
 'image_lowquality': 'https://external.fakl8-1.fna.fbcdn.net/safe_image.php?d=AQGNPjoHChbMoLgZ&w=476&h=249&url=https%3A%2F%2Fwww.twiddy.com%2Fblog%2Fwp-content%2Fuploads%2F2019%2F08%2FNOBBC_flight2.jpg&cfs=1&jq=75&ext=jpg&_nc_oe=6f6ca&_nc_sid=06c271&ccb=3-5&gt=1&_nc_hash=AQGM7mkGSq_Qd5Ps',
 'images': ['https://www.twiddy.com/blog/wp-content/uploads/2019/08/NOBBC_flight2.jpg'],
 'images_description': [],
 'images_lowquality': ['https://external.fakl8-1.fna.fbcdn.net/safe_image.php?d=AQGNPjoHChbMoLgZ&w=476&h=249&url=https%3A%2F%2Fwww.twiddy.com%2Fblog%2Fwp-content%2Fuploads%2F2019%2F08%2FNOBBC_flight2.jpg&cfs=1&jq=75&ext=jpg&_nc_oe=6f6ca&_nc_sid=06c271&ccb=3-5&gt=1&_nc_hash=AQGM7mkGSq_Qd5Ps'],
 'images_lowquality_description': [None],
 'is_live': False,
 'likes': 25,
 'link': 'https://www.twiddy.com/y7QWb?fbclid=IwAR33fE6cEVE7699zPm2SWzy36VkE1iSOS06PF-rSRv_DUjWsapEsOQ3AfXs',
 'links': [{'link': 'https://lm.facebook.com/l.php?u=https%3A%2F%2Fwww.twiddy.com%2Fy7QWb%3Ffbclid%3DIwAR33fE6cEVE7699zPm2SWzy36VkE1iSOS06PF-rSRv_DUjWsapEsOQ3AfXs&h=AT0qIxWb_Tay8_GdXdR5H83XysOCxll-40teY8JnrgIKYNBUWZItWqBzlsXlXgi5FzTUdUfEWuRS81gkO96h5O28WiMSNORC5EnJnqQL5eGrDOSWkY1O-k-TT94ymUxG_1r-a5MTly4djuF-LhhPMk1s3ZYA',
            'text': 'https://www.twiddy.com/y7QWb'},
           {'link': '/hashtag/twiddyobx?refid=52&__tn__=%2As-R',
            'text': '#twiddyobx'},
           {'link': '/hashtag/twiddyvacation?refid=52&__tn__=%2As-R',
            'text': '#twiddyvacation'},
           {'link': '/hashtag/twiddyblog?refid=52&__tn__=%2As-R',
            'text': '#twiddyblog'},
           {'link': '/hashtag/localobx?refid=52&__tn__=%2As-R',
            'text': '#localobx'},
           {'link': '/hashtag/shoplocal?refid=52&__tn__=%2As-R',
            'text': '#shoplocal'},
           {'link': '/hashtag/breweries?refid=52&__tn__=%2As-R',
            'text': '#breweries'},
           {'link': '/hashtag/rainydays?refid=52&__tn__=%2As-R',
            'text': '#rainydays'},
           {'link': '/hashtag/cheers?refid=52&__tn__=%2As-R',
            'text': '#cheers'}],
 'original_request_url': '10158228969136398',
 'page_id': '19600366397',
 'post_id': '10158228969136398',
 'post_text': "Looking for something to do during these rainy days? 🌧 We've "
              'got you covered! ☔️ Check out this list of our favorite '
              'breweries around OBX: https://www.twiddy.com/y7QWb. 🍻\n'
              '.\n'
              '.\n'
              '.\n'
              '#twiddyobx #twiddyvacation #twiddyblog #localobx #shoplocal '
              '#breweries #rainydays #cheers',
 'post_url': 'https://facebook.com/story.php?story_fbid=10158228969136398&id=19600366397',
 'reaction_count': 28,
 'reactions': {'like': 25, 'love': 3},
 'reactors': [{'link': 'https://facebook.com/brock.kirchner.94?fref=pb',
               'name': 'Brock Kirchner',
               'type': 'like'},
              {'link': 'https://facebook.com/profile.php?id=100007437975587&fref=pb',
               'name': 'Matti Minute',
               'type': 'like'},
              {'link': 'https://facebook.com/jon.ludwig.733?fref=pb',
               'name': 'Jon Ludwig',
               'type': 'like'},
              {'link': 'https://facebook.com/bill.spencer.1257?fref=pb',
               'name': 'Bill Spencer',
               'type': 'like'},
              {'link': 'https://facebook.com/jim.sedgmer?fref=pb',
               'name': 'Jim Sedgmer',
               'type': 'like'},
              {'link': 'https://facebook.com/szcztkwsk?fref=pb',
               'name': 'Cathy Jaskowiak Szczutkowski',
               'type': 'like'},
              {'link': 'https://facebook.com/cassey.boss?fref=pb',
               'name': 'Cassey Wheatley',
               'type': 'like'},
              {'link': 'https://facebook.com/belinda.reed.18?fref=pb',
               'name': 'Belinda Reed',
               'type': 'like'},
              {'link': 'https://facebook.com/chris.wuertz.71?fref=pb',
               'name': 'Chris Wuertz',
               'type': 'like'},
              {'link': 'https://facebook.com/melissa.cicci.7?fref=pb',
               'name': 'Melissa Cicci',
               'type': 'like'},
              {'link': 'https://facebook.com/danielle.mayberrynilson?fref=pb',
               'name': 'Danielle Mayberry Nilson',
               'type': 'like'},
              {'link': 'https://facebook.com/marilyn.narozny?fref=pb',
               'name': 'Marilyn Narozny',
               'type': 'like'},
              {'link': 'https://facebook.com/nupur.koplinka?fref=pb',
               'name': 'Nupur Shah Koplinka',
               'type': 'like'},
              {'link': 'https://facebook.com/becky.powel2012l?fref=pb',
               'name': 'Becky Powell',
               'type': 'like'},
              {'link': 'https://facebook.com/profile.php?id=1483362366&fref=pb',
               'name': 'Matt Forry',
               'type': 'like'},
              {'link': 'https://facebook.com/michael.dengler.71?fref=pb',
               'name': 'Michael Dengler',
               'type': 'like'},
              {'link': 'https://facebook.com/profile.php?id=1394218024&fref=pb',
               'name': 'Scott H. Afflerbach',
               'type': 'like'},
              {'link': 'https://facebook.com/lorenz.bruce?fref=pb',
               'name': 'Bruce Lorenz',
               'type': 'like'},
              {'link': 'https://facebook.com/susan.s.mcelhinney?fref=pb',
               'name': 'Susan McElhinney',
               'type': 'like'},
              {'link': 'https://facebook.com/sean.jamison.37?fref=pb',
               'name': 'Sean Jamison',
               'type': 'love'},
              {'link': 'https://facebook.com/douglas.w.smith.121?fref=pb',
               'name': 'Douglas W Smith',
               'type': 'love'},
              {'link': 'https://facebook.com/taylor.aljian?fref=pb',
               'name': 'Taylor Augusta',
               'type': 'love'},
              {'link': 'https://facebook.com/doro.54?fref=pb',
               'name': 'Dorothy Root',
               'type': 'like'},
              {'link': 'https://facebook.com/ryan.humphrey.9889?fref=pb',
               'name': 'Ryan Humphrey',
               'type': 'like'},
              {'link': 'https://facebook.com/robyn.duskin?fref=pb',
               'name': 'Robyn Duskin Connelly',
               'type': 'like'},
              {'link': 'https://facebook.com/nicole.cosper1?fref=pb',
               'name': 'Nicole Cosper',
               'type': 'like'},
              {'link': 'https://facebook.com/courtney.sedon?fref=pb',
               'name': 'Courtney Sedon',
               'type': 'like'},
              {'link': 'https://facebook.com/emily.kellish?fref=pb',
               'name': 'Emily Wyrzykowski',
               'type': 'like'}],
 'shared_post_id': None,
 'shared_post_url': None,
 'shared_text': 'TWIDDY.COM\n'
                'Outer Banks Beer Guide: Best Craft Beer, Microbreweries & '
                'More | Twiddy',
 'shared_time': None,
 'shared_user_id': None,
 'shared_username': None,
 'sharers': None,
 'shares': 1,
 'text': "Looking for something to do during these rainy days? 🌧 We've got you "
         'covered! ☔️ Check out this list of our favorite breweries around '
         'OBX: https://www.twiddy.com/y7QWb. 🍻\n'
         '.\n'
         '.\n'
         '.\n'
         '#twiddyobx #twiddyvacation #twiddyblog #localobx #shoplocal '
         '#breweries #rainydays #cheers\n'
         '\n'
         'TWIDDY.COM\n'
         'Outer Banks Beer Guide: Best Craft Beer, Microbreweries & More | '
         'Twiddy',
 'time': datetime.datetime(2021, 8, 5, 9, 7, 54),
 'timestamp': 1628111274,
 'user_id': '19600366397',
 'user_url': 'https://facebook.com/TwiddyOuterBanks/?refid=52&__tn__=C-R',
 'username': 'Twiddy & Co',
 'video': None,
 'video_duration_seconds': None,
 'video_height': None,
 'video_id': None,
 'video_quality': None,
 'video_size_MB': None,
 'video_thumbnail': None,
 'video_watches': None,
 'video_width': None,
 'w3_fb_url': 'https://www.facebook.com/story.php?story_fbid=10158228969136398&id=19600366397',
 'was_live': False,
 'with': None}
```

19600366397 is the numeric ID for the TwiddyOuterBanks page. The timeline_cursor is what determines what page of posts.

**Comment by msaljoug** [comment]
you are a legend!

**Comment by evildrome** [comment]
Am I doing something stupid?

my code is


`cookies_file = ("C:/python-progs/data/FB Groups/cookies.json")

import time
from facebook_scraper import *

results = []
start_url = None
def handle_pagination_url(url):
    global start_url
    start_url = url
    if results:
        print(f"{len(results)}: {results[-1]['time']}: {start_url}")
set_cookies(cookies_file)
while True:
    try:
        for post in get_posts("TwiddyOuterBanks", page_limit=None, start_url=start_url, request_url_callback=handle_pagination_url, options={
            "allow_extra_requests": False,
            "posts_per_page": 200
        }):
            results.append(post)
        print("All done")
        break
    except exceptions.TemporarilyBanned:
        print("Temporarily banned, sleeping for 10m")
        time.sleep(600) `
        
        
And when I run it I get :

Python 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.22.0 -- An enhanced Interactive Python.

runfile('C:/python-progs/untitled1.py', wdir='C:/python-progs')
C:\Users\wilson\anaconda3\envs\Python 38\lib\site-packages\facebook_scraper\facebook_scraper.py:235: UserWarning: Locale detected as en_GB - for best results, set to en_US
  warnings.warn(f"Locale detected as {locale} - for best results, set to en_US")
Traceback (most recent call last):

  File "C:\python-progs\untitled1.py", line 23, in <module>
    for post in get_posts("TwiddyOuterBanks", page_limit=None, start_url=start_url, request_url_callback=handle_pagination_url, options={

  File "C:\Users\wilson\anaconda3\envs\Python 38\lib\site-packages\facebook_scraper\facebook_scraper.py", line 333, in _generic_get_posts
    for i, page in zip(counter, iter_pages_fn()):

  File "C:\Users\wilson\anaconda3\envs\Python 38\lib\site-packages\facebook_scraper\page_iterators.py", line 29, in iter_pages
    return generic_iter_pages(start_url, PageParser, request_fn, **kwargs)

TypeError: generic_iter_pages() got multiple values for argument 'start_url'

**Comment by micjgam** [comment]
Just three quick questions to all of this...

1.  How long is the temp ban (I just got one as well)?
2.  I am still able to login to my account on the front end, so where is the actual temp ban taking place?
3.  With what frequency can I run the scraper and get away from the temp ban?

**Comment by neon-ninja** [comment]
@evildrome what version of facebook-scraper do you have? (`pip freeze | grep facebook`)

@micjgam
1. about an hour
2. it's also specific to that set of cookies
3. depends on how many requests you're making

**Comment by micjgam** [comment]
> 

Thanks!

3. Pulling only 1-3 pages at a time <100 posts.  My usage for this script is specific.

**Comment by neon-ninja** [comment]
Just the posts, no comments?

**Comment by evildrome** [comment]
Hi Nick, 

 facebook-scraper==0.2.38
 
 Cheers,
 
   Wilson.

**Comment by evildrome** [comment]
Full disclosure, I have Python 2.7 and 3.8 environments in Anaconda & I run the scraper in 3.8

**Comment by micjgam** [comment]
I only need the posts for now... there might be a greater use case in the future.

Keep up the good work!

**Comment by neon-ninja** [comment]
@evildrome 0.2.38 is 8 months old. Try upgrade to 0.2.52 (`pip install -U facebook-scraper`). The scraper does not work in Python 2.7 (Python 2.7 is is End Of Life). Python 3.8 should work fine.

@micjgam then I think that should be fine. Hourly should be possible, if that what you need

**Comment by evildrome** [comment]
Oh dear... error: Microsoft Visual C++ 14.0 or greater is required.

If I do Add / Remove programs it shows me  Visual C++ 5, 8, 10, 12, 13 and 15 - 22.

However if I do Get-WmiObject -Class Win32_Product -Filter "Name LIKE '%Visual C++ 201%'"

it shows me 

IdentifyingNumber : {1D8E6291-B0D5-35EC-8441-6616F567A0F7}
Name              : Microsoft Visual C++ 2010  x64 Redistributable - 10.0.40219
Vendor            : Microsoft Corporation
Version           : 10.0.40219
Caption           : Microsoft Visual C++ 2010  x64 Redistributable - 10.0.40219

IdentifyingNumber : {F0C3E5D1-1ADE-321E-8167-68EF0DE699A5}
Name              : Microsoft Visual C++ 2010  x86 Redistributable - 10.0.40219
Vendor            : Microsoft Corporation
Version           : 10.0.40219
Caption           : Microsoft Visual C++ 2010  x86 Redistributable - 10.0.40219

IdentifyingNumber : {13A4EE12-23EA-3371-91EE-EFB36DDFFF3E}
Name              : Microsoft Visual C++ 2013 x86 Minimum Runtime - 12.0.21005
Vendor            : Microsoft Corporation
Version           : 12.0.21005
Caption           : Microsoft Visual C++ 2013 x86 Minimum Runtime - 12.0.21005

IdentifyingNumber : {F8CFEB22-A2E7-3971-9EDA-4B11EDEFC185}
Name              : Microsoft Visual C++ 2013 x86 Additional Runtime - 12.0.21005
Vendor            : Microsoft Corporation
Version           : 12.0.21005
Caption           : Microsoft Visual C++ 2013 x86 Additional Runtime - 12.0.21005

IdentifyingNumber : {929FBD26-9020-399B-9A7A-751D61F0B942}
Name              : Microsoft Visual C++ 2013 x64 Additional Runtime - 12.0.21005
Vendor            : Microsoft Corporation
Version           : 12.0.21005
Caption           : Microsoft Visual C++ 2013 x64 Additional Runtime - 12.0.21005

IdentifyingNumber : {A749D8E6-B613-3BE3-8F5F-045C84EBA29B}
Name              : Microsoft Visual C++ 2013 x64 Minimum Runtime - 12.0.21005
Vendor            : Microsoft Corporation
Version           : 12.0.21005
Caption           : Microsoft Visual C++ 2013 x64 Minimum Runtime - 12.0.21005

IdentifyingNumber : {37B8F9C7-03FB-3253-8781-2517C99D7C00}
Name              : Microsoft Visual C++ 2012 x64 Additional Runtime - 11.0.61030
Vendor            : Microsoft Corporation
Version           : 11.0.61030
Caption           : Microsoft Visual C++ 2012 x64 Additional Runtime - 11.0.61030

IdentifyingNumber : {B175520C-86A2-35A7-8619-86DC379688B9}
Name              : Microsoft Visual C++ 2012 x86 Additional Runtime - 11.0.61030
Vendor            : Microsoft Corporation
Version           : 11.0.61030
Caption           : Microsoft Visual C++ 2012 x86 Additional Runtime - 11.0.61030

IdentifyingNumber : {CF2BEA3C-26EA-32F8-AA9B-331F7E34BA97}
Name              : Microsoft Visual C++ 2012 x64 Minimum Runtime - 11.0.61030
Vendor            : Microsoft Corporation
Version           : 11.0.61030
Caption           : Microsoft Visual C++ 2012 x64 Minimum Runtime - 11.0.61030

IdentifyingNumber : {BD95A8CD-1D9F-35AD-981A-3E7925026EBB}
Name              : Microsoft Visual C++ 2012 x86 Minimum Runtime - 11.0.61030
Vendor            : Microsoft Corporation
Version           : 11.0.61030
Caption           : Microsoft Visual C++ 2012 x86 Minimum Runtime - 11.0.61030

**Comment by neon-ninja** [comment]
See https://github.com/kevinzg/facebook-scraper/issues/591

**Comment by evildrome** [comment]
Hi Nick,  

 I modified my Visual Studio install to include the VC 14 runtime + the Win 10 SDK.
 
 After that I was able to update the facebook-scraper in Anaconda & the handle_pagination_url code now works for me!
 
 Cheers,
 
 Wilson.
