### ISSUE TITLE
Scraping Posts on a Page breaks post_text resulting blank outputs

### ISSUE THREAD

**Issue by blaterwolf** [kevinzg/facebook-scraper#687]
When scraping a page's data, `post_text` key value is missing and only returns a blank string.

Back in December, I was able to pull all posts from the page that I am scraping on. But since I accidentally deleted the December CSV file for it, I am now doing it again. I used the code referenced in #637 because I have been getting temporary blocks from scraping 1198 posts. I was able to check the number of posts because of the code in #285 and I'm pretty sure that in my December CSV file the discrepancy of the posts is just about a ~100 or so (1090+ from what I can remember). (this is important later)

Code:

```python
from facebook_scraper import *
import pandas as pd
import os
import time

results = []
start_url = None
start = time.time()


def handle_pagination_url(url):
    global start_url
    start_url = url


set_cookies("cookies.txt")
while True:
    try:
        for post in get_posts("FactCheckPhils", page_limit=None, start_url=start_url, request_url_callback=handle_pagination_url):
            os.system("cls")
            results.append(post)
            print(
                f"{len(results)} retrieved in {round(time.time() - start)}s.")
            if(len(results) == 50):
                break
        print("ALL DONE. Saving to csv.")
        dataset = pd.DataFrame.from_records(results)
        dataset.to_csv('new_dataset.csv', index=False)
        print("Saved to csv.")
        break
    except exceptions.TemporarilyBanned:
        print("Temporarily banned, sleeping for 10m")
        time.sleep(600)
```

There are two datasets that I have generated for this post. I only gathered 50 posts to summarize the data:
- [with_options_dataset.csv](https://github.com/kevinzg/facebook-scraper/files/8121655/with_options_dataset.csv) - this dataset has
 an `options` parameter: `options={"allow_extra_requests": False, "posts_per_page": 200}`
- [without_options_dataset.csv](https://github.com/kevinzg/facebook-scraper/files/8121656/without_options_dataset.csv) - this dataset doesn't have an `options` parameter.

The summary of the difference of both files is that:
- `with_options_dataset.csv` was only able to retrieve 2/50 of the `post_text` key value.
- `without_options_dataset.csv` retrieved 22/50 of the `post_text` key value.

I did the full 1198 posts but it stopped at the 22nd post and then it just only retrieves blank.

I only have 2 suspicions with what is happening:
1. It has something to do with the retrieval process - to which I am contesting since I was able to pull all posts from the December CSV file without even using cookies at that time.
2. It has something to do with the 22nd post's text that is breaking - which can be found [here](https://www.facebook.com/FactCheckPhils/posts/5080947765330787)

To mention, since a post's JSON data consists of either `text` and `post_text`, both of these key values return the full text. But interestingly, the `text` retrieves only the partial text that we can only see before we click the "See More" and it has the page name on the first part which does not happen on the 1st-22nd posts.

**Comment by neon-ninja** [comment]
I'm unable to reproduce this error without options - for me, all 50 posts have post_text populated. Perhaps you run into some sort of Exception that I don't, but I can't tell as you haven't provided debug logs.

With options however, I get this Exception:

```python
Requesting page from: https://m.facebook.com/page_content_list_view/more/?page_id=1624618274297104&start_cursor={"timeline_cursor":"AQHRDRbyl6_2uzNmC9X4R_LuHaX495jbz_G0E2VrMeZEYk1huxQFIfaEiU-xRCxIij2ESE_3vlQXjc9yfgo-Tv1dlsQ8sFG7SmolsH3cEgDqCZfwTvGVdzm7Qf2rmLjvoTS2","timeline_section_cursor":null,"has_next_page":true}&num_to_fetch=200&surface_type=posts_tab
Exception while requesting URL: https://m.facebook.com/page_content_list_view/more/?page_id=1624618274297104&start_cursor={"timeline_cursor":"AQHRDRbyl6_2uzNmC9X4R_LuHaX495jbz_G0E2VrMeZEYk1huxQFIfaEiU-xRCxIij2ESE_3vlQXjc9yfgo-Tv1dlsQ8sFG7SmolsH3cEgDqCZfwTvGVdzm7Qf2rmLjvoTS2","timeline_section_cursor":null,"has_next_page":true}&num_to_fetch=200&surface_type=posts_tab
Exception: HTTPError('500 Server Error: Internal Server Error for url: https://m.facebook.com/page_content_list_view/more/?page_id=1624618274297104&start_cursor=%7B%22timeline_cursor%22:%22AQHRDRbyl6_2uzNmC9X4R_LuHaX495jbz_G0E2VrMeZEYk1huxQFIfaEiU-xRCxIij2ESE_3vlQXjc9yfgo-Tv1dlsQ8sFG7SmolsH3cEgDqCZfwTvGVdzm7Qf2rmLjvoTS2%22,%22timeline_section_cursor%22:null,%22has_next_page%22:true%7D&num_to_fetch=200&surface_type=posts_tab&locale=en_US')
Traceback (most recent call last):
  File "/home/nyou045/git/facebook-scraper/facebook_scraper/facebook_scraper.py", line 795, in get
    response.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://m.facebook.com/page_content_list_view/more/?page_id=1624618274297104&start_cursor=%7B%22timeline_cursor%22:%22AQHRDRbyl6_2uzNmC9X4R_LuHaX495jbz_G0E2VrMeZEYk1huxQFIfaEiU-xRCxIij2ESE_3vlQXjc9yfgo-Tv1dlsQ8sFG7SmolsH3cEgDqCZfwTvGVdzm7Qf2rmLjvoTS2%22,%22timeline_section_cursor%22:null,%22has_next_page%22:true%7D&num_to_fetch=200&surface_type=posts_tab&locale=en_US
Caught exception, retry number 1. Sleeping for 2s
```
I think 200 is too high a value for posts_per_page for this page. Try 50, that seems to work OK. The reason the extraction results change, is that the scraper has this retry code:

https://github.com/kevinzg/facebook-scraper/blob/8397f43afe5423b98b7b4eea1ef7e1e0c2d484f3/facebook_scraper/page_iterators.py#L89

After the 3rd failed attempt, the scraper switches into noscript mode. This is essentially the same as mbasic.facebook.com. This can be seen in the debug logs when this occurs:

```python
Caught exception, retry number 3. Sleeping for 6s
Requesting noscript
Requesting page from: https://m.facebook.com/page_content_list_view/more/?page_id=1624618274297104&start_cursor={"timeline_cursor":"AQHRDRbyl6_2uzNmC9X4R_LuHaX495jbz_G0E2VrMeZEYk1huxQFIfaEiU-xRCxIij2ESE_3vlQXjc9yfgo-Tv1dlsQ8sFG7SmolsH3cEgDqCZfwTvGVdzm7Qf2rmLjvoTS2","timeline_section_cursor":null,"has_next_page":true}&num_to_fetch=200&surface_type=posts_tab
Parsing page response
Got 189 raw posts from page
Extracting posts from page 1
```

mbasic does not provide like counts or share counts, which is why those show as 0.

So, the root cause of this issue is that noscript post text extraction isn't working correctly. For testing purposes, you can call `set_noscript(True)` to manually enable it. Note how noscript post extraction misinterprets the post text as shared text. This is because noscript posts have a nested header element, so the first two elements of this nodes array (https://github.com/kevinzg/facebook-scraper/blob/d1aa4692a4d04a5cf82956053c71845673d310e1/facebook_scraper/extractors.py#L271) are both header elements (one top level one, and the other header element within it).

https://github.com/kevinzg/facebook-scraper/commit/9e456e4c877a508b401dbe5db62615d51a26404e should fix this issue. This should also fix the issue of the page name (coming from the header) incorrectly making it into `text`
