### ISSUE TITLE
Getting the issue of unsupported browser for facebook

### ISSUE THREAD

**Issue by MussabMehboob** [kevinzg/facebook-scraper#718]
I am attaching an image showing the problem.  I am getting this error. 
warnings.warn(f"Facebook says 'Unsupported Browser'")
Traceback (most recent call last):
  File "C:\Users\Mussab\PycharmProjects\Facebook Scraper\main.py", line 2, in <module>
    get_group_info("Python Developer Connect", cookies="cookie.txt")
  File "C:\Users\Mussab\PycharmProjects\Facebook Scraper\venv\lib\site-packages\facebook_scraper\__init__.py", line 126, in get_group_info
    return _scraper.get_group_info(group, **kwargs)
  File "C:\Users\Mussab\PycharmProjects\Facebook Scraper\venv\lib\site-packages\facebook_scraper\facebook_scraper.py", line 665, in get_group_info
    resp = self.get(url).html
  File "C:\Users\Mussab\PycharmProjects\Facebook Scraper\venv\lib\site-packages\facebook_scraper\facebook_scraper.py", line 829, in get
    raise exceptions.UnexpectedResponse("Your request couldn't be processed")
facebook_scraper.exceptions.UnexpectedResponse: Your request couldn't be processed

<img width="926" alt="issue" src="https://user-images.githubusercontent.com/99961872/159423994-7e6696d6-30b2-4632-a487-e08f0cfbddc2.PNG">

**Comment by weg38asyy** [comment]
try it, adding a user agent.

```python=
from facebook_scraper import *

set_user_agent(
    "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)")
```

This worked for me.

**Comment by neon-ninja** [comment]
You need to pass the group id, not name. `"pythonconnect"` instead of `"Python Developers Connect"`

**Comment by wgicio** [comment]
facebook-scraper 350448261731413 

I am also getting this error message when passing the ID

**Comment by jpkrop** [comment]
I have the same error now (first time, before all works good). I add the user agent as the post of @weg38asyy but this time I not have error message but I have a new problem, result is not complete (maybe 5%).

Do you know why ?

**Comment by neon-ninja** [comment]
@wgicio is that the full command?

@jpkrop I wouldn't recommend using that user agent

**Comment by wgicio** [comment]
@neon-ninja 
`facebook-scraper 350448261731413 --filename 20220410_350448261731413.csv --cookies fbcookie.txt --group --sleep 4 --pages 15 --days-limit 14 --k post_id,text,time,image,images,link,post_url,user_id,username,listing_price,page_id --encoding utf8 --verbose -nm $'We are looking for|massage|im looking for|hello all|hello dear|HAIR COLOUR|hello everybody|hello friends|hi guys|hello guys|hi there|hello there|carpenter|jeep|moving service|we are a couple|i am looking for|Scooter Rental|i\'m looking for|we\'re looking for' -m '081|082|085|086|087|089|628|62 8|62-8|wa.me|whatsapp|Whats App|Dm|Pm|message'`

**Comment by neon-ninja** [comment]
Using that command generates a CSV with 21 rows, so it seems to be working fine for me

**Comment by neon-ninja** [comment]
Maybe try update to the latest version

**Comment by Nabeelyousaf** [comment]
Hey i m getting this error 
C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\facebook_scraper\facebook_scraper.py:841: UserWarning: Facebook says 'Unsupported Browser'
  warnings.warn(f"Facebook says 'Unsupported Browser'")
![image](https://user-images.githubusercontent.com/68015136/163377551-277d0c0e-ff9b-4afb-a21a-9538068e0680.png)

**Comment by Nabeelyousaf** [comment]
@neon-ninja  any solution about it

**Comment by neon-ninja** [comment]
It's not an error, just a warning. It's safe to ignore

**Comment by Nabeelyousaf** [comment]
@neon-ninja ok got it 
hey, can I get Facebook page info?

**Comment by neon-ninja** [comment]
Yes. `get_profile` returns a dict. Try `print` it to console

**Comment by Nabeelyousaf** [comment]
hey @neon-ninja  i m getting this exception

**Comment by neon-ninja** [comment]
Then pass cookies as per the readme

**Comment by Nabeelyousaf** [comment]
@neon-ninja  i m getting new error 
![image](https://user-images.githubusercontent.com/68015136/163529700-1a99fc7a-2286-4503-a820-a16d65704298.png)

**Comment by neon-ninja** [comment]
The cookies.txt file needs to be in the same directory as where you run the script from

**Comment by Nabeelyousaf** [comment]
hey @neon-ninja  i m getting new error 
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\facebook_scraper\__init__.py", line 48, in set_cookies
    raise exceptions.InvalidCookies(f"Missing cookies with name(s): {missing_cookies}")
facebook_scraper.exceptions.InvalidCookies: Missing cookies with name(s): ['c_user', 'xs']
![image](https://user-images.githubusercontent.com/68015136/163538122-ac85a699-a95f-49ce-8e7b-e314e114ec94.png)

**Comment by Nabeelyousaf** [comment]
> The cookies.txt file needs to be in the same directory as where you run the script from

ok got it ,

**Comment by Nabeelyousaf** [comment]
hey @neon-ninja can you give me some detail why i m getting this error and how i can solved it

**Comment by neon-ninja** [comment]
Make sure your cookies.txt includes those cookies (with the names c_user and xs)

**Comment by sahullander** [comment]
For those trying to figure out the cookie.txt information:
1) Login to facebook.
2) Once logged in, right click anywehere on the page and select "Inspect".
3) At the top pf the developer panel, select the "Application" tab.
4) On the left side of the developer panel, find the "Storage" section and and expand the "Cookies" item (this should show the facebook URL once expanded).
5) Copy each "Name" and "Value" item into "cookies.txt" in a JSON format and save "cookies.txt".

Example "cookies.txt":
`
{
        "xs" : "val1",
        "wd" : "val2",
        "usida" : "val3",
        "sb" : "val4",
        "presence" : "val5",
        "locale" : "val6",
        "fr" : "val7",
        "dpr" : "val8",
        "datr" : "val9",
        "c_user" : "val9"
}
`

**Comment by haidergillani** [comment]
Hey @neon-ninja any help on why my kernel keeps dying whenever I run the scrapping command? 
![image](https://user-images.githubusercontent.com/116860085/201252415-edbd1205-7f9d-4071-9961-7c65bc70d42d.png)
