### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'html' when I use get_profile

### ISSUE THREAD

**Issue by chrioikon** [kevinzg/facebook-scraper#796]
I am using Python version 3.8.10 and I get the following exception:
Traceback (most recent call last):
  File "example.py", line 2, in <module>
    print(get_profile("zuck"))
  File "/lib/python3.8/site-packages/facebook_scraper/__init__.py", line 84, in get_profile
    return _scraper.get_profile(account, **kwargs)
  File "/lib/python3.8/site-packages/facebook_scraper/facebook_scraper.py", line 323, in get_profile
    top_post = PostExtractor(top_post, kwargs, self.get).extract_post()
  File "/lib/python3.8/site-packages/facebook_scraper/extractors.py", line 204, in extract_post
    has_more = self.more_url_regex.search(self.element.html)
AttributeError: 'NoneType' object has no attribute 'html'

on the simple:
from facebook_scraper import *
print(get_profile("zuck"))

**Comment by neon-ninja** [comment]
Try pass cookies as per the readme

**Comment by chrioikon** [comment]
Yeah. That seems to fix the problem but it has limited information. The about tab seems to not get scrapped.
