### ISSUE TITLE
Not able to retrieve reviews from a page anymore

### ISSUE THREAD

**Issue by YovelD** [kevinzg/facebook-scraper#838]
Hi everyone,

I tried to retrieve reviews from a page but am getting errors.

```
from facebook_scraper import *
from pprint import pprint

set_cookies("facebook.com_cookies.txt")
set_user_agent("Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)")

for review in get_page_info("trumilou")['reviews']:
    pprint(review)
```

The error I get  : 

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [165], in <cell line: 7>()
      4 set_cookies("facebook.com_cookies.txt")
      5 set_user_agent("Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)")
----> 7 for review in get_page_info("trumilou")['reviews']:
      8     pprint(review)

KeyError: 'reviews'
```

When I try pprint(get_page_info("trumilou")), I don't get info about reviews either : 

```
{'Basic info': 'Birthday',
 'Category': 'Restaurant français',
 'Contact info': "84, Quai de l'Hôtel de Ville, Paris, France\n"
                 'Address\n'
                 '/Trumilou\n'
                 'Facebook',
 'Follower_count': None,
 'Following_count': 2,
 'Friend_count': None,
 'Life events': '',
 'Name': 'Le Trumilou',
 'Page transparency\nSee all': 'See all\n'
                               'Facebook is showing information to help you '
                               'understand the purpose of this Page.\n'
                               'November 27, 2010\n'
                               'Creation date\n'
                               'Admin info\n'
                               'This Page can have multiple admins. They may '
                               'have permission to post content, comment or '
                               'send messages as the Page.\n'
                               'This Page is not currently running ads.',
 'Price Range': '$$',
 'active_ads_link': 'https://m.facebook.com/pages/transparency/159260050783557/active_ads/?refid=17',
 'address': "84, Quai de l'Hôtel de Ville, Paris, France",
 'cover_photo': 'https://scontent-cdt1-1.xx.fbcdn.net/v/t39.30808-6/215022377_196728859125058_6063362988450442177_n.jpg?stp=cp0_dst-jpg_e15_fr_q65&_nc_cat=101&ccb=1-7&_nc_sid=dd9801&efg=eyJpIjoidCJ9&_nc_ohc=TGOgr0OWlboAX8mXoUo&tn=H9LctpD8sGvxXGlR&_nc_ht=scontent-cdt1-1.xx&oh=00_AT-_kNo-GxWlCj2vVT8ePI_6MDitz4UeaTam60FapBaUPA&oe=62F8835A&manual_redirect=1',
 'cover_photo_text': "Cover Photo: Le Trumilou's photo.",
 'email': 'contact@letrumilou.fr',
 'followers': 517,
 'map_link': 'https://maps.google.com/maps?q=84%2C+Quai+de+l%27H%C3%B4tel+de+Ville%2C+Paris%2C+France&hl=fr&fbclid=IwAR35lEMEPdU3l4IbBjoVodj52USFZa_8Gl4oqZ2l-u1CYIKcRgxpHECC1uA',
 'phone': '+33142776398',
 'profile_picture': 'https://scontent-cdg2-1.xx.fbcdn.net/v/t1.6435-9/212401306_195694512561826_5027175418670550353_n.jpg?stp=cp0_dst-jpg_e15_fr_q65&_nc_cat=107&ccb=1-7&_nc_sid=85a577&efg=eyJpIjoidCJ9&_nc_ohc=nhVhZ2JJrG4AX96MXfm&_nc_ht=scontent-cdg2-1.xx&oh=00_AT8PWDOc7cmUIPTC0k9uTdabUKm7JjWKO2MUhooLuhzeqQ&oe=6317FC5D&manual_redirect=1',
 'rating': '',
 'top_post': {'available': True,
              'comments': 3,
              'comments_full': None,
              'factcheck': None,
              'header': 'Le Trumilou is at Le Trumilou.',
              'image': 'https://scontent-cdt1-1.xx.fbcdn.net/v/t39.30808-6/297954053_471115631686378_1137085708228715894_n.jpg?stp=cp0_dst-jpg_e15_fr_q65&_nc_cat=110&ccb=1-7&_nc_sid=8024bb&efg=eyJpIjoidCJ9&_nc_ohc=Uj1W0sIDS8cAX8hEzWe&_nc_ht=scontent-cdt1-1.xx&oh=00_AT_KtFtF6Unc7PCfohBUG_03dz49L9aNEOqunl5vKxUSsg&oe=62F9382F&manual_redirect=1',
              'image_id': '471115638353044',
              'image_ids': ['471115638353044'],
              'image_lowquality': 'https://scontent-cdt1-1.xx.fbcdn.net/v/t39.30808-6/297954053_471115631686378_1137085708228715894_n.jpg?stp=cp0_dst-jpg_e15_fr_q65&_nc_cat=110&ccb=1-7&_nc_sid=8024bb&efg=eyJpIjoidCJ9&_nc_ohc=Uj1W0sIDS8cAX8hEzWe&_nc_ht=scontent-cdt1-1.xx&oh=00_AT_KtFtF6Unc7PCfohBUG_03dz49L9aNEOqunl5vKxUSsg&oe=62F9382F',
              'images': ['https://scontent-cdt1-1.xx.fbcdn.net/v/t39.30808-6/297954053_471115631686378_1137085708228715894_n.jpg?stp=cp0_dst-jpg_e15_fr_q65&_nc_cat=110&ccb=1-7&_nc_sid=8024bb&efg=eyJpIjoidCJ9&_nc_ohc=Uj1W0sIDS8cAX8hEzWe&_nc_ht=scontent-cdt1-1.xx&oh=00_AT_KtFtF6Unc7PCfohBUG_03dz49L9aNEOqunl5vKxUSsg&oe=62F9382F&manual_redirect=1'],
              'images_description': ['May be an image of mountain, nature, '
                                     'grass and tree'],
              'images_lowquality': ['https://scontent-cdt1-1.xx.fbcdn.net/v/t39.30808-6/297954053_471115631686378_1137085708228715894_n.jpg?stp=cp0_dst-jpg_e15_fr_q65&_nc_cat=110&ccb=1-7&_nc_sid=8024bb&efg=eyJpIjoidCJ9&_nc_ohc=Uj1W0sIDS8cAX8hEzWe&_nc_ht=scontent-cdt1-1.xx&oh=00_AT_KtFtF6Unc7PCfohBUG_03dz49L9aNEOqunl5vKxUSsg&oe=62F9382F'],
              'images_lowquality_description': ['May be an image of mountain, '
                                                'nature, grass and tree'],
              'is_live': False,
              'likes': 29,
              'link': None,
              'links': [{'link': '/story.php?story_fbid=pfbid02125yFcVFk3irpUsBTaY4banwXNCUk5uUDprg2VQEPQeCbH39rwUZ44z5BbCsWgi7l&id=100063638347002&refid=17',
                         'text': 'More'},
                        {'link': '/hashtag/bonnesvacances?refid=17',
                         'text': '#bonnesvacances'},
                        {'link': '/hashtag/trumilou?refid=17',
                         'text': '#trumilou'},
                        {'link': '/hashtag/letrumilou?refid=17',
                         'text': '#letrumilou'},
                        {'link': '/hashtag/restaurant?refid=17',
                         'text': '#restaurant'},
                        {'link': '/hashtag/faitmaison?refid=17',
                         'text': '#faitmaison'},
                        {'link': '/hashtag/homemade?refid=17',
                         'text': '#homemade'},
                        {'link': '/hashtag/restaurantparis?refid=17',
                         'text': '#restaurantparis'},
                        {'link': '/hashtag/foodlove?refid=17',
                         'text': '#foodlove'},
                        {'link': '/hashtag/frenchfood?refid=17',
                         'text': '#frenchfood'},
                        {'link': '/hashtag/suggestionduchef?refid=17',
                         'text': '#suggestionduchef'},
                        {'link': '/hashtag/foodstagram?refid=17',
                         'text': '#foodstagram'},
                        {'link': '/hashtag/auvergne?refid=17',
                         'text': '#Auvergne'},
                        {'link': '/hashtag/foodinparis?refid=17',
                         'text': '#foodinparis'},
                        {'link': '/hashtag/parisfood?refid=17',
                         'text': '#parisfood'},
                        {'link': '/hashtag/summer2022?refid=17',
                         'text': '#summer2022'},
                        {'link': '/hashtag/été2022?refid=17',
                         'text': '#été2022'},
                        {'link': '/hashtag/vacances?refid=17',
                         'text': '#vacances'},
                        {'link': '/hashtag/bonnesvacances?refid=17',
                         'text': '#bonnesvacances'},
                        {'link': '/hashtag/holiday?refid=17',
                         'text': '#holiday'},
                        {'link': '/hashtag/auvergnetourisme?refid=17',
                         'text': '#Auvergnetourisme'},
                        {'link': '/hashtag/myauvergne?refid=17',
                         'text': '#myAuvergne'},
                        {'link': '/hashtag/goodvibes?refid=17',
                         'text': '#goodvibes'}],
              'original_text': None,
              'page_id': '159260050783557',
              'post_id': '471115671686374',
              'post_text': "Bonnes vacances ! 🌞 L'équipe du Trumilou vous "
                           'souhaite un excellente été 2022 et a hâte de vous '
                           'retrouver à la rentrée ❤\n'
                           '\n'
                           "Bisous d'Auvergne 😘\n"
                           '\n'
                           '.\n'
                           '.\n'
                           '.\n'
                           'Le Trumilou, restaurant familial depuis 1964\n'
                           "📍 84, quai de l'Hôtel de Ville 75004 Paris\n"
                           'Ⓜ️ Hôtel de Ville (1 & 11) / Pont-Marie (7)\n'
                           '☎️ +33 (0)1 42 77 63 98\n'
                           '\n'
                           '.\n'
                           '.\n'
                           '\n'
                           '#bonnesvacances #trumilou #letrumilou #restaurant '
                           '#faitmaison #homemade #restaurantparis #foodlove '
                           '#frenchfood #suggestionduchef #foodstagram '
                           '#Auvergne #foodinparis #parisfood #summer2022 '
                           '#été2022 #vacances #bonnesvacances #holiday '
                           '#Auvergnetourisme #myAuvergne #goodvibes',
              'post_url': 'https://facebook.com/story.php?story_fbid=pfbid02125yFcVFk3irpUsBTaY4banwXNCUk5uUDprg2VQEPQeCbH39rwUZ44z5BbCsWgi7l&id=100063638347002',
              'reaction_count': None,
              'reactions': None,
              'reactors': None,
              'shared_post_id': None,
              'shared_post_url': None,
              'shared_text': '',
              'shared_time': None,
              'shared_user_id': None,
              'shared_username': None,
              'sharers': None,
              'shares': 1,
              'text': "Bonnes vacances ! 🌞 L'équipe du Trumilou vous souhaite "
                      'un excellente été 2022 et a hâte de vous retrouver à la '
                      'rentrée ❤\n'
                      '\n'
                      "Bisous d'Auvergne 😘\n"
                      '\n'
                      '.\n'
                      '.\n'
                      '.\n'
                      'Le Trumilou, restaurant familial depuis 1964\n'
                      "📍 84, quai de l'Hôtel de Ville 75004 Paris\n"
                      'Ⓜ️ Hôtel de Ville (1 & 11) / Pont-Marie (7)\n'
                      '☎️ +33 (0)1 42 77 63 98\n'
                      '\n'
                      '.\n'
                      '.\n'
                      '\n'
                      '#bonnesvacances #trumilou #letrumilou #restaurant '
                      '#faitmaison #homemade #restaurantparis #foodlove '
                      '#frenchfood #suggestionduchef #foodstagram #Auvergne '
                      '#foodinparis #parisfood #summer2022 #été2022 #vacances '
                      '#bonnesvacances #holiday #Auvergnetourisme #myAuvergne '
                      '#goodvibes',
              'time': datetime.datetime(2022, 8, 7, 11, 28, 43),
              'timestamp': 1659864523,
              'user_id': '100063638347002',
              'user_url': 'https://facebook.com/Trumilou?lst=1602706715%3A100063638347002%3A1660120674&refid=17',
              'username': 'Le Trumilou',
              'video': None,
              'video_duration_seconds': None,
              'video_height': None,
              'video_id': None,
              'video_quality': None,
              'video_size_MB': None,
              'video_thumbnail': None,
              'video_watches': None,
              'video_width': None,
              'w3_fb_url': None,
              'was_live': False,
              'with': [{'link': 'https://facebook.com/Trumilou?refid=17',
                        'name': 'Le Trumilou'}]}}
```

I'm using Facebook Scraper 0.2.58.

**Comment by YovelD** [comment]
With logging enabled : 

```python
Requesting page from: /trumilou/about/
Requesting page from: /trumilou/about/
Requesting page from: /trumilou/about/
Requesting page from: /trumilou/about/
Requesting page from: /trumilou/
Requesting page from: /trumilou/
Requesting page from: /trumilou/
Requesting page from: /trumilou/
No ld+json element
No ld+json element
No ld+json element
No ld+json element
Requesting page from: /trumilou/community
Requesting page from: /trumilou/community
Requesting page from: /trumilou/community
Requesting page from: /trumilou/community
Exception while requesting URL: https://m.facebook.com/trumilou/community
Exception: HTTPError('404 Client Error: Not Found for url: https://m.facebook.com/trumilou/community?locale=en_US')
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\facebook_scraper\facebook_scraper.py", line 644, in get_page_info
    ld_json = resp.html.find("script[type='application/ld+json']", first=True).text
AttributeError: 'NoneType' object has no attribute 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\facebook_scraper\facebook_scraper.py", line 852, in get
    response.raise_for_status()
  File "C:\Program Files\Python310\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://m.facebook.com/trumilou/community?locale=en_US
Exception while requesting URL: https://m.facebook.com/trumilou/community
Exception: HTTPError('404 Client Error: Not Found for url: https://m.facebook.com/trumilou/community?locale=en_US')
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\facebook_scraper\facebook_scraper.py", line 644, in get_page_info
    ld_json = resp.html.find("script[type='application/ld+json']", first=True).text
AttributeError: 'NoneType' object has no attribute 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\facebook_scraper\facebook_scraper.py", line 852, in get
    response.raise_for_status()
  File "C:\Program Files\Python310\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://m.facebook.com/trumilou/community?locale=en_US
Exception while requesting URL: https://m.facebook.com/trumilou/community
Exception: HTTPError('404 Client Error: Not Found for url: https://m.facebook.com/trumilou/community?locale=en_US')
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\facebook_scraper\facebook_scraper.py", line 644, in get_page_info
    ld_json = resp.html.find("script[type='application/ld+json']", first=True).text
AttributeError: 'NoneType' object has no attribute 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\facebook_scraper\facebook_scraper.py", line 852, in get
    response.raise_for_status()
  File "C:\Program Files\Python310\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://m.facebook.com/trumilou/community?locale=en_US
Exception while requesting URL: https://m.facebook.com/trumilou/community
Exception: HTTPError('404 Client Error: Not Found for url: https://m.facebook.com/trumilou/community?locale=en_US')
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\facebook_scraper\facebook_scraper.py", line 644, in get_page_info
    ld_json = resp.html.find("script[type='application/ld+json']", first=True).text
AttributeError: 'NoneType' object has no attribute 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\facebook_scraper\facebook_scraper.py", line 852, in get
    response.raise_for_status()
  File "C:\Program Files\Python310\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://m.facebook.com/trumilou/community?locale=en_US
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
Requesting page from: trumilou
Requesting page from: trumilou
Requesting page from: trumilou
Requesting page from: trumilou
Got exact timestamp from publish_time: 2022-08-07 11:28:43
Got exact timestamp from publish_time: 2022-08-07 11:28:43
Got exact timestamp from publish_time: 2022-08-07 11:28:43
Got exact timestamp from publish_time: 2022-08-07 11:28:43
Fetching https://m.facebook.com/photo.php?fbid=471115638353044&id=100063638347002&set=a.195694489228495&source=48&refid=17
Fetching https://m.facebook.com/photo.php?fbid=471115638353044&id=100063638347002&set=a.195694489228495&source=48&refid=17
Fetching https://m.facebook.com/photo.php?fbid=471115638353044&id=100063638347002&set=a.195694489228495&source=48&refid=17
Fetching https://m.facebook.com/photo.php?fbid=471115638353044&id=100063638347002&set=a.195694489228495&source=48&refid=17
Fetching https://m.facebook.com/photo/view_full_size/?fbid=471115638353044&ref_component=mbasic_photo_permalink&ref_page=%2Fwap%2Fphoto.php&refid=13
Fetching https://m.facebook.com/photo/view_full_size/?fbid=471115638353044&ref_component=mbasic_photo_permalink&ref_page=%2Fwap%2Fphoto.php&refid=13
Fetching https://m.facebook.com/photo/view_full_size/?fbid=471115638353044&ref_component=mbasic_photo_permalink&ref_page=%2Fwap%2Fphoto.php&refid=13
Fetching https://m.facebook.com/photo/view_full_size/?fbid=471115638353044&ref_component=mbasic_photo_permalink&ref_page=%2Fwap%2Fphoto.php&refid=13
[471115671686374] Extract method extract_video didn't return anything
[471115671686374] Extract method extract_video didn't return anything
[471115671686374] Extract method extract_video didn't return anything
[471115671686374] Extract method extract_video didn't return anything
[471115671686374] Extract method extract_video_thumbnail didn't return anything
[471115671686374] Extract method extract_video_thumbnail didn't return anything
[471115671686374] Extract method extract_video_thumbnail didn't return anything
[471115671686374] Extract method extract_video_thumbnail didn't return anything
[471115671686374] Extract method extract_video_id didn't return anything
[471115671686374] Extract method extract_video_id didn't return anything
[471115671686374] Extract method extract_video_id didn't return anything
[471115671686374] Extract method extract_video_id didn't return anything
Fetching 471115671686374
Fetching 471115671686374
Fetching 471115671686374
Fetching 471115671686374
[471115671686374] Extract method extract_video_meta didn't return anything
[471115671686374] Extract method extract_video_meta didn't return anything
[471115671686374] Extract method extract_video_meta didn't return anything
[471115671686374] Extract method extract_video_meta didn't return anything
[471115671686374] Extract method extract_factcheck didn't return anything
[471115671686374] Extract method extract_factcheck didn't return anything
[471115671686374] Extract method extract_factcheck didn't return anything
[471115671686374] Extract method extract_factcheck didn't return anything
[471115671686374] Extract method extract_share_information didn't return anything
[471115671686374] Extract method extract_share_information didn't return anything
[471115671686374] Extract method extract_share_information didn't return anything
[471115671686374] Extract method extract_share_information didn't return anything
[471115671686374] Extract method extract_listing didn't return anything
[471115671686374] Extract method extract_listing didn't return anything
[471115671686374] Extract method extract_listing didn't return anything
[471115671686374] Extract method extract_listing didn't return anything
Friend_count extraction failed: list index out of range
Friend_count extraction failed: list index out of range
Friend_count extraction failed: list index out of range
Friend_count extraction failed: list index out of range
Follower_count extraction failed: 'NoneType' object has no attribute 'text'
Follower_count extraction failed: 'NoneType' object has no attribute 'text'
Follower_count extraction failed: 'NoneType' object has no attribute 'text'
Follower_count extraction failed: 'NoneType' object has no attribute 'text'
Fetching /trumilou?v=following
Fetching /trumilou?v=following
Fetching /trumilou?v=following
Fetching /trumilou?v=following
Fetching https://m.facebook.com/photo/view_full_size/?fbid=196728852458392&ref_component=mbasic_photo_permalink&ref_page=%2Fwap%2Fphoto.php&refid=13
Fetching https://m.facebook.com/photo/view_full_size/?fbid=196728852458392&ref_component=mbasic_photo_permalink&ref_page=%2Fwap%2Fphoto.php&refid=13
Fetching https://m.facebook.com/photo/view_full_size/?fbid=196728852458392&ref_component=mbasic_photo_permalink&ref_page=%2Fwap%2Fphoto.php&refid=13
Fetching https://m.facebook.com/photo/view_full_size/?fbid=196728852458392&ref_component=mbasic_photo_permalink&ref_page=%2Fwap%2Fphoto.php&refid=13
Fetching https://m.facebook.com/photo/view_full_size/?fbid=195694505895160&ref_component=mbasic_photo_permalink&ref_page=%2Fwap%2Fphoto.php&refid=13
Fetching https://m.facebook.com/photo/view_full_size/?fbid=195694505895160&ref_component=mbasic_photo_permalink&ref_page=%2Fwap%2Fphoto.php&refid=13
Fetching https://m.facebook.com/photo/view_full_size/?fbid=195694505895160&ref_component=mbasic_photo_permalink&ref_page=%2Fwap%2Fphoto.php&refid=13
Fetching https://m.facebook.com/photo/view_full_size/?fbid=195694505895160&ref_component=mbasic_photo_permalink&ref_page=%2Fwap%2Fphoto.php&refid=13
Requesting page from: https://m.facebook.com/trumilou/about/
Requesting page from: https://m.facebook.com/trumilou/about/
Requesting page from: https://m.facebook.com/trumilou/about/
Requesting page from: https://m.facebook.com/trumilou/about/
```

**Comment by neon-ninja** [comment]
Try pass the reviews=True argument to get_page_info. Alternatively pass reviews="generator" to get a generator back.

**Comment by YovelD** [comment]
Thank you for your answer. 
I still can't seem to be able to get reviews, with either reviews=True or reviews="generator". I'm not sure how to use _scraper.get_page_reviews. 

```python
from facebook_scraper import *
from pprint import pprint
import tqdm as notebook_tqdm

set_cookies("facebook.com_cookies.txt")
set_user_agent("Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)")

for review in get_page_info("trumilou", reviews=True)['reviews']:
    pprint(review)
```


```python
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\facebook_scraper\utils.py", line 279, in safe_consume
    for item in generator:
  File "C:\Program Files\Python310\lib\site-packages\facebook_scraper\facebook_scraper.py", line 555, in get_page_reviews
    response = self.get(more_url)
  File "C:\Program Files\Python310\lib\site-packages\facebook_scraper\facebook_scraper.py", line 852, in get
    response.raise_for_status()
  File "C:\Program Files\Python310\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://m.facebook.com/trumilou/reviews?locale=en_US
```

**Comment by neon-ninja** [comment]
https://m.facebook.com/trumilou/reviews?locale=en_US doesn't work in my browser either, this page must have reviews disabled

**Comment by YovelD** [comment]
Non mobile version works : https://www.facebook.com/Trumilou/reviews/?locale=en_US, which is weird. Do you know what could be happening ? I can't get any mobile page to work with reviews.

**Comment by neon-ninja** [comment]
https://m.facebook.com/pg/SkyTowerAKL/reviews/ works fine
