### ISSUE TITLE
Doesn't support special characters

### ISSUE THREAD

**Issue by gentrexha** [kevinzg/facebook-scraper#84]
Running `facebook-scraper --filename IKSHPK_page_posts.csv --pages 1 IKSHPK` produces this error. Due to the special character '\u0113' (ë) I'm assuming.

Using:
* Windows 10
* Python 3.7

Output:
```
(kosovo-covid-data) C:\Projects\Personal\kosovo-covid-data>facebook-scraper --filename IKSHPK_page_posts.csv --pages 1 IKSHPK
Traceback (most recent call last):
  File "C:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\Virtual Environments\kosovo-covid-data\Scripts\facebook-scraper.exe\__main__.py", line 7, in <module>
  File "c:\users\user\virtual environments\kosovo-covid-data\lib\site-packages\facebook_scraper\__main__.py", line 33, in run
    write_posts_to_csv(**kwargs, filename=args.filename, pages=args.pages)
  File "c:\users\user\virtual environments\kosovo-covid-data\lib\site-packages\facebook_scraper\__init__.py", line 97, in write_posts_to_csv
    dict_writer.writerows(list_of_posts)
  File "C:\Python37\lib\csv.py", line 158, in writerows
    return self.writer.writerows(map(self._dict_to_list, rowdicts))
  File "C:\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0113' in position 717: character maps to <undefined>
```

Proposed solution, change line in `__init__.py`:

from:

```
with open(filename, 'w') as output_file:
```

to

```
with open(filename, 'w', encoding='utf-8') as output_file:
```

**Comment by kevinzg** [comment]
Python should use the preferred encoding for your system, which in your case it seems to be Windows-1252.
But I guess we could add an option to change the encoding.

**Comment by kevinzg** [comment]
I added an optional encoding parameter for `write_posts_to_csv` and for the command line: `--encoding utf-8`.
