### ISSUE TITLE
Test Case Probe Error. Content Not Found

### ISSUE THREAD

**Issue by xlonn23** [kevinzg/facebook-scraper#847]
Instruction code:

```
from facebook_scraper import *
get_group_info("latesthairstyles", cookies="cookies.txt")
```

Error:

```
Traceback (most recent call last):
  File "C:\Users\NASA\Desktop\07\2022\test3\main.py", line 2, in <module>
    get_group_info("latesthairstyles", cookies="cookies.txt")
  File "C:\Users\NASA\Desktop\07\2022\test3\venv\lib\site-packages\facebook_scraper\__init__.py", line 143, in get_group_info
    return _scraper.get_group_info(group, **kwargs)
  File "C:\Users\NASA\Desktop\07\2022\test3\venv\lib\site-packages\facebook_scraper\facebook_scraper.py", line 727, in get_group_info
    resp = self.get(url).html
  File "C:\Users\NASA\Desktop\07\2022\test3\venv\lib\site-packages\facebook_scraper\facebook_scraper.py", line 905, in get
    raise exceptions.NotFound(title.text)
facebook_scraper.exceptions.NotFound: Content Not Found

Process finished with exit code 1
```

**Comment by xlonn23** [comment]
Solved the problem by using get_page_info instead of get_group_info.

**Comment by xlonn23** [comment]
But I wonder why the get_group_info function does not work. It doesn't matter which page is accessed - the "Content Not Found" error is raised..

**Comment by neon-ninja** [comment]
Looks like this group was removed from FB, I've updated the README example in https://github.com/kevinzg/facebook-scraper/commit/2552c6f0188e9d7de894e0828106e3f011c6b110
