### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'cookies.json'

### ISSUE THREAD

**Issue by sinanajluan** [kevinzg/facebook-scraper#856]
Traceback (most recent call last):
  File "C:\Users\Lenovo T440p\PycharmProjects\facebook-scraper\ProveLuani.py", line 19, in <module>
    post = next(get_posts(post_urls=['nintendo'], cookies="cookies.json", options={"comments":True, "progress": True}))
  File "C:\Users\Lenovo T440p\PycharmProjects\facebook-scraper\facebook_scraper\__init__.py", line 196, in get_posts
    set_cookies(cookies)
  File "C:\Users\Lenovo T440p\PycharmProjects\facebook-scraper\facebook_scraper\__init__.py", line 40, in set_cookies
    cookies = parse_cookie_file(cookies)
  File "C:\Users\Lenovo T440p\PycharmProjects\facebook-scraper\facebook_scraper\utils.py", line 221, in parse_cookie_file
    with open(filename, mode='rt') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'cookies.json'

Process finished with exit code 1

**Comment by NielsOerbaek** [comment]
Is the `cookies.json`-file in the same folder as your script?
