### ISSUE TITLE
Your request couldn't be processed (UnexpectedResponse)

### ISSUE THREAD

**Issue by mossmoss** [kevinzg/facebook-scraper#857]
I'm running 0.2.58 and receive the following error: 

`
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/facebook_scraper/__init__.py", line 438, in write_posts_to_csv
    for post in get_posts(
  File "/home/user/.local/lib/python3.8/site-packages/facebook_scraper/facebook_scraper.py", line 1092, in _generic_get_posts
    for i, page in zip(counter, iter_pages_fn()):
  File "/home/user/.local/lib/python3.8/site-packages/facebook_scraper/page_iterators.py", line 92, in generic_iter_pages
    response = request_fn(next_url)
  File "/home/user/.local/lib/python3.8/site-packages/facebook_scraper/facebook_scraper.py", line 899, in get
    raise exceptions.UnexpectedResponse("Your request couldn't be processed")
facebook_scraper.exceptions.UnexpectedResponse: Your request couldn't be processed
Couldn't get any posts.
`

My command looks like: 

`
/usr/bin/python3 /home/user/.local/bin/facebook-scraper -c="/home/user/Downloads/facebook.com_cookies.txt" --filename page_posts.csv --pages 3 facebook-user
`

**Comment by mossmoss** [comment]
Duplicate  of #849

**Comment by mossmoss** [comment]
Duplicate of https://github.com/kevinzg/facebook-scraper/issues/849
