### ISSUE TITLE
any solution?

### ISSUE THREAD

**Issue by epktt** [kevinzg/facebook-scraper#934]
im getting this 

`Exception while requesting URL: https://m.facebook.com/XXXXXXX/
Exception: TooManyRedirects('Exceeded 30 redirects.')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/facebook_scraper/facebook_scraper.py", line 871, in get
    response = self.session.get(url=url, **self.requests_kwargs, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 668, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 165, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/facebook_scraper/__init__.py", line 441, in write_posts_to_csv
    for post in get_posts(
  File "/usr/local/lib/python3.8/dist-packages/facebook_scraper/facebook_scraper.py", line 1114, in _generic_get_posts
    for i, page in zip(counter, iter_pages_fn()):
  File "/usr/local/lib/python3.8/dist-packages/facebook_scraper/page_iterators.py", line 87, in generic_iter_pages
    response = request_fn(next_url)
  File "/usr/local/lib/python3.8/dist-packages/facebook_scraper/facebook_scraper.py", line 871, in get
    response = self.session.get(url=url, **self.requests_kwargs, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 668, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 165, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
Couldn't get any posts.
`

**Comment by NielsOerbaek** [comment]
Hi! I had the same issue, and it seems that increasing the user-agents to the current safari-standard works.
I've added a pull request here: https://github.com/kevinzg/facebook-scraper/pull/949/commits/1e78ad5800c900611cfd1e01cf3f8c8f5f43e5d7
