### ISSUE TITLE
get_posts not working properly

### ISSUE THREAD

**Issue by Alanjv05** [kevinzg/facebook-scraper#969]
I´ve been using get_posts for a couple of months with no issue until a couple of days ago.
Suddenly it didn't get any of the reactions from the posts so I tried setting my facebook language to English because I was using it in Spanish but when it´s in english it keeps saying my account is temporarily blocked even though I can still access facebook through my browser without any problem.
Setting "allow_extra_requests":False makes it work but without the reactions.
I've already tried setting "reactors":True but it didn't work.
When I set my facebook language back to Spanish it works with the "allow_extra_requests":True but it just gets the reactions from a few posts but not all of them.

Note: Only in English I get the "Facebook says 'Unsupported Browser'" and the " You’re Temporarily Blocked" exception.

Here's the code I try to use:

```
from facebook_scraper import get_posts

options = {"comments": True, "reactors": True, "allow_extra_requests": True, "posts_per_page": 5}
for post in get_posts("nintendo", pages = 10, cookies = "facebook.com_cookies.txt", options = options):
    print(post["text"])
    print(post["comments"])
    print(post["shares"])
    print(post["comment_text"])

    try:
        print(post["reactions"])
    except:
        pass
```

**Comment by sirreyson** [comment]
Same issue here, this has happened to me as of last week.
Sometimes passing the cookies instead of a username and password fixes the reaction problem but it never works twice.
The DataFrame is created correctly, but all of the posts (rows) have 'None' values in columns such as: 'comments_full, reactors, reactions, sharers', columns like 'likes, comments, shares, reaction_count' default to 0 despite the fact those posts DO have reactions and comments.

The only constant error I get is:
```
Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\facebook_scraper\utils.py", line 279, in safe_consume
    for item in generator:
  File "D:\Anaconda\lib\site-packages\facebook_scraper\extractors.py", line 774, in extract_sharers
    more = response.html.find("#m_more_item a", first=True)
  File "D:\Anaconda\lib\site-packages\requests_html.py", line 212, in find
    for found in self.pq(selector)
  File "D:\Anaconda\lib\site-packages\pyquery\pyquery.py", line 256, in __call__
    result = self._copy(*args, parent=self, **kwargs)
  File "D:\Anaconda\lib\site-packages\pyquery\pyquery.py", line 242, in _copy
    return self.__class__(*args, **kwargs)
  File "D:\Anaconda\lib\site-packages\pyquery\pyquery.py", line 227, in __init__
    xpath = self._css_to_xpath(selector)
  File "D:\Anaconda\lib\site-packages\pyquery\pyquery.py", line 238, in _css_to_xpath
    return self._translator.css_to_xpath(selector, prefix)
  File "D:\Anaconda\lib\site-packages\cssselect\xpath.py", line 190, in css_to_xpath
    return ' | '.join(self.selector_to_xpath(selector, prefix,
  File "D:\Anaconda\lib\site-packages\cssselect\xpath.py", line 190, in <genexpr>
    return ' | '.join(self.selector_to_xpath(selector, prefix,
  File "D:\Anaconda\lib\site-packages\cssselect\xpath.py", line 219, in selector_to_xpath
    xpath = self.xpath(tree)
  File "D:\Anaconda\lib\site-packages\cssselect\xpath.py", line 254, in xpath
    return method(parsed_selector)
  File "D:\Anaconda\lib\site-packages\cssselect\xpath.py", line 263, in xpath_combinedselector
    return method(self.xpath(combined.selector),
  File "D:\Anaconda\lib\site-packages\cssselect\xpath.py", line 356, in xpath_descendant_combinator
    return left.join('/descendant-or-self::*/', right)
  File "D:\Anaconda\lib\site-packages\pyquery\cssselectpatch.py", line 34, in join
    res = XPathExprOrig.join(self, combiner, other,
TypeError: join() got an unexpected keyword argument 'closing_combiner'
```

**Comment by ReemOmer** [comment]
I am also experiencing the same issue, I tried creating a new Facebook account and use its cookies, yet, the problem still persists. Changing the IP address doesn't help as well.

**Comment by Sinchana-SS** [comment]
Any update regarding this issue?
It was working fine with the same code till last week, and suddenly I'm getting an error:
TypeError: join() got an unexpected keyword argument 'closing_combiner'

**Comment by HYLZ-2019** [comment]
> Any update regarding this issue? It was working fine with the same code till last week, and suddenly I'm getting an error: TypeError: join() got an unexpected keyword argument 'closing_combiner'

I searched to this page because one of my students had the same error message using PyQuery. It was probably because a mismatched library version. She uninstalled pyquery with pip and installed it with anaconda, and the problem was solved.
