### ISSUE TITLE
Error with cookies file

### ISSUE THREAD

**Issue by mossmoss** [kevinzg/facebook-scraper#979]
I'm trying to run facebook-scraper on a Mac (Monterey) with homebrew installed python3 and pip3 - and pip3 installed facebook-scraper - I'm running into an issue I'm not sure how to resolve. I saved my cookies with "Get cookies.txt" plugin in Chrome for facebook.com both c_user and xs are present. On a first save the domains listed are .facebook.com - later visits also have www.facebook.com entries. I tried with both cookie files and received the same error, though it complains about a different cookie on the second saved cookie file:

`
~/facebook via 🐘 via 🐍 v3.11.2 
❯ /usr/local/bin/python3 /usr/local/bin/facebook-scraper -c="/Users/user/Downloads/facebook.com_cookies.txt" --filename zuck.csv --pages 3 zuck
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/facebook_scraper/utils.py", line 225, in parse_cookie_file
    data = json.loads(data)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/facebook_scraper/utils.py", line 265, in parse_cookie_file
    domain, _, path, secure, expires, name, value = line.split('\t')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 7)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/facebook_scraper/__init__.py", line 441, in write_posts_to_csv
    for post in get_posts(
                ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/facebook_scraper/__init__.py", line 196, in get_posts
    set_cookies(cookies)
  File "/usr/local/lib/python3.11/site-packages/facebook_scraper/__init__.py", line 40, in set_cookies
    cookies = parse_cookie_file(cookies)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/facebook_scraper/utils.py", line 267, in parse_cookie_file
    raise exceptions.InvalidCookies(f"Can't parse line {i + 1}: '{line}'")
facebook_scraper.exceptions.InvalidCookies: Can't parse line 5: '.facebook.com	TRUE	/	TRUE	1704048735	datr	XGC_6UIunU3urMG	28'
Couldn't get any posts.
`

Thanks for any help!

**Comment by PitBosch** [comment]
I have the same error

**Comment by mossmoss** [comment]
@PitBosch Do you think it might be some newer python module? Maybe the latest Get cookies.txt change?  

I have a WSL2/Ubuntu system where facebook-scraper 0.2.59 is working -

```
❯ pip3 freeze|grep -i json
demjson==2.2.4
demjson3==3.0.5
fastjsonschema==2.16.1
json5==0.9.10
jsonpatch==1.22
jsonpointer==2.0
jsonschema==3.2.0
simplejson==3.16.0
```

I have 2 Mac laptops where 0.2.59 doesn't work. I frequently brew update/upgrade - on these, there is only

```
❯ pip3 freeze|grep -i json
demjson3==3.0.6
```

Maybe some modules are missing or are too new on the Mac?

**Comment by pvgandhi404** [comment]
I had the same issue. Try using another extension like [edit this cookie](https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg?hl=en), copy the cookies and store them in a JSON file instead.

**Comment by mossmoss** [comment]
> I had the same issue. Try using another extension like [edit this cookie](https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg?hl=en), copy the cookies and store them in a JSON file instead.

This worked for me on my previously broken Macs! I'm wondering why text format cookies are working on my other system and my Macs seem to want JSON cookies?

**Comment by supremeconset** [comment]
You need to disable cookie size value on plugin.
![image](https://user-images.githubusercontent.com/10571043/223021724-4153b57d-7b97-4feb-898b-abb5f9042370.png)
